### ISSUE TITLE
Error: connect ETIMEDOUT  in China

### ISSUE THREAD

**Issue by allan-simon** [Medium/phantomjs#147]
Well first it seems that the link http://cdn.bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-i686.tar.bz2 link  time out in China 

so maybe propose if possible alternative download link in timeout error.

it's quite a pity otherwise as phantomjs is used by a lot of node js package (including angular-js seed application)

**Comment by ShadowRZ** [comment]
'Cause they are using Amazon S3.
