### ISSUE TITLE
Windows: 'node install.js' hangs if there is already a version installed globally

### ISSUE THREAD

**Issue by xelibrion** [Medium/phantomjs#149]
I was installing _karma-phantomjs-launcher_ module, which has a dependency on phantomjs, and it suddenly got stuck at the point when it supposed to run _install.js_

It looks like the problem is caused by these lines of code:

``` JavaScript
var checkVersionDeferred = kew.defer()
cp.execFile(phantomPath, ['--version'], checkVersionDeferred.makeNodeResolver())
```

The **phantomPath** variable in my case is pointing to _c:\Users<username>\AppData\Roaming\npm\phantomjs.cmd_ file

``` Shell
PhantomJS is already installed at C:\Users\<username>\AppData\Roaming\npm\phantomjs.CMD.
```

and asking it for a version is not quite working:

``` Shell
$ phantomjs.cmd --version
./phantomjs.cmd: line 1: syntax error near unexpected token `('
./phantomjs.cmd: line 1: `@IF EXIST "%~dp0\node.exe" ('
```

It works though if you drop _.cmd_ extension

``` Shell
$ phantomjs --version
1.9.7
```

The version I was trying to install was 1.9.7. 
The workaround for this problem was to install phantomjs globally.

**Comment by otacon507** [comment]
Xelibrion, I am having a similar problem, only when I try to run npm install globally or locally I get hung up on 
 phantomjs@1.9.18 install c:\Source\node_modules\phantomjs
 node install.js 

I tried changing exports.version to another version # in 
phantomjs\lib\phantomjs.js file;

Same problem still.. Any suggestions?
