### ISSUE TITLE
npm install on Debian fails

### ISSUE THREAD

**Issue by martinlindhe** [Medium/phantomjs#157]
Hello!
Running "npm install" to set up project depencencies locally failed on this:

> phantomjs@1.9.7-5 install /home/ml/dev/traceur-test/traceur-test/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! phantomjs@1.9.7-5 install: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.7-5 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ml/dev/traceur-test/traceur-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE

[.. snip...]

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ml/dev/traceur-test/traceur-test/npm-debug.log
npm ERR! not ok code 0

In /usr/share/doc/nodejs/README.Debian one can read:
## nodejs command

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.

**Comment by frankie-loves-jesus** [comment]
Thanks for the fix @martinlindhe!
