### ISSUE TITLE
Publish a non-pre-release version of 1.9

### ISSUE THREAD

**Issue by dylang** [Medium/phantomjs#222]
`npm 2.0.0` will probably be released [in a few days](https://github.com/npm/npm/issues/6043). It includes an [updated semver](https://github.com/npm/node-semver) which more strickly follows the [semver standard](semver.org). 

This means when users type to `"phantomjs": "~1.9"`, it will not find a matching version in the registry because only pre-release versions (`x.y.z-n`) have been published.

The error message looks like  this:

```
npm install phantomjs@~1.9
npm ERR! Darwin 13.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "phantomjs@~1.9"
npm ERR! node v0.10.31
npm ERR! npm  v2.0.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: phantomjs@'>=1.9.0 <1.10.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","1.8.0-1","1.8.1-1","1.8.1-2","1.8.1-3","1.8.2-0","1.8.2-1","1.8.2-2","1.9.0-0","1.9.0-1","1.9.0-2","1.9.0-3","1.9.0-4","1.9.0-5","1.9.0-6","1.9.1-0","1.9.1-2","1.9.1-3","1.9.1-4","1.9.1-5","1.9.1-6","1.9.1-7","1.9.1-8","1.9.1-9","1.9.2-0","1.9.2-1","1.9.2-2","1.9.2-3","1.9.2-4","1.9.2-5","1.9.2-6","1.9.6-0","1.9.7-1","1.9.7-3","1.9.7-4","1.9.7-5","1.9.7-6","1.9.7-7","1.9.7-8","1.9.7-9","1.9.7-10","1.9.7-11","1.9.7-12","1.9.7-13","1.9.7-14","1.9.7-15","1.8.2-3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
```

A fix is tell anybody using `phantomjs 1.9` to specify the pre-release tag in their package.json, such as `"phantomjs": "^1.9.0-0"`, or to publish to npm a version of `phantomjs` that is `1.9.x` with no `-number` suffix.

**Comment by boompig** [comment]
This is still an issue for me.
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.14
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: phantomjs@'>=1.8.1 <1.9.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","1.8.0-1","1.8.1-1","1.8.1-2","1.8.1-3","1.8.2-0","1.8.2-1","1.8.2-2","1.9.0-0","1.9.0-1","1.9.0-2","1.9.0-3","1.9.0-4","1.9.0-5","1.9.0-6","1.9.1-0","1.9.1-2","1.9.1-3","1.9.1-4","1.9.1-5","1.9.1-6","1.9.1-7","1.9.1-8","1.9.1-9","1.9.2-0","1.9.2-1","1.9.2-2","1.9.2-3","1.9.2-4","1.9.2-5","1.9.2-6","1.9.6-0","1.9.7-1","1.9.7-3","1.9.7-4","1.9.7-5","1.9.7-6","1.9.7-7","1.9.7-8","1.9.7-9","1.9.7-10","1.9.7-11","1.9.7-12","1.9.7-13","1.9.7-14","1.9.7-15","1.8.2-3","1.9.8","1.9.9","1.9.10","1.9.11","1.9.12","1.9.13","1.9.15"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dbkats/prog/passzero/bower_components/jquery-ui/npm-debug.log

**Comment by nicks** [comment]
@boompig you should upgrade your phantomjs version.
