### ISSUE TITLE
Error when trying to install via NPM and via Yeoman WebApp generator

### ISSUE THREAD

**Issue by jknopp** [Medium/phantomjs#232]
When trying to run 'yo webapp' I get an error saying "Error: Cannot find module 'C:\Development\install.js'" even though the directory I am installing in is C:\Development\Test\. I also tried just installing via NPM without Yeoman and I get the same error...

<pre><code>
> phantomjs@1.9.10 install C:\Development\test\node_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Development\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:811:3

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs"
npm ERR! node v0.11.14-nightly-20140819-pre
npm ERR! npm  v2.0.2
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.10 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.10 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Development\test'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, rmdir 'C:\Development\test']
npm ERR! error rolling back   stack: 'Error: EBUSY, rmdir \'C:\\Development\\tes
t\'\n    at Error (native)',
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Development\\test' }
</code></pre>

**Comment by robkinyon** [comment]
I started having this problem when going to 1.9.8. I removed the upgraded request version and everything worked seamlessly again. This is installing from Artifactory's NPM support, if that matters. But, it was pretty consistent with both 0.10.31, 0.10.32, and upgrading npm to 2.1.4

**Comment by nicks** [comment]
I am closing this bug because there is no further action we can take on this. NPM is failing before it even gets to the phantomjs installer.

**Comment by devdRew** [comment]
I fixed that with upgrading `node` and `npm` to latest, then removing `node_modules` directory and run `npm install` again.

Upgrade node: http://davidwalsh.name/upgrade-nodejs
Upgrade npm: http://stackoverflow.com/questions/23393707/how-to-update-npm
