### ISSUE TITLE
Error making request. Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by linchong899201** [Medium/phantomjs#244]
jxdeveloper003@jxdeveloper003-Precision-T3600:/var/www/angularjs/angular-seed$ sudo npm install
[sudo] password for jxdeveloper003: 
npm WARN optional dep failed, continuing fsevents@0.2.1
 
> ws@0.4.32 install /var/www/angularjs/angular-seed/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/www/angularjs/angular-seed/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/www/angularjs/angular-seed/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
\
> phantomjs@1.9.11 install /var/www/angularjs/angular-seed/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
Saving to /var/www/angularjs/angular-seed/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

**Comment by nicks** [comment]
TIMEDOUT typically means the network download failed, and is an expected failure if there are problems with your network.
