### ISSUE TITLE
PhantomJS binary and NPM package version numbers are inconsistent and confusing

### ISSUE THREAD

**Issue by Jaxsun** [Medium/phantomjs#270]
PhantomJS' package.json states that it is version 1.9.13, this is also what is shown on the npm page for PhantomJS. However when PhantomJS is run it states that it is version 1.9.8. This is very confusing, as it seems to imply that NPM is downloading the incorrect version when in fact everything is correctly updated to the latest.

**Comment by nicks** [comment]
We actually had a discussion with the NPM people about this. See https://github.com/Medium/phantomjs/issues/222. Unfortunately, this is not really feasible to fix, given the constraints imposed by semver.
