### ISSUE TITLE
[io.js v1.0.1] Certificate error causing phantomjs install to fail

### ISSUE THREAD

**Issue by pheuter** [Medium/phantomjs#271]
```sh
$ npm install
```

```
node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/hw/6bcr1lnj4n94tfw8z0k13fjr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:895:36)
    at TLSSocket.emit (events.js:92:17)
    at TLSSocket._finishInit (_tls_wrap.js:438:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.0.1
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.13 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    ./npm-debug.log
```

**Comment by nicks** [comment]
filed as https://github.com/iojs/io.js/issues/402

given that io.js v1.0.1 is currently marked beta, I don't think we should try to work around this in this package (as it's a pretty far-reaching openssl problem)

**Comment by pheuter** [comment]
Gotcha, makes sense.

**Comment by corbinu** [comment]
That issue has been fixed how ever when installing phantomjs on iojs the install now gets stuck and never stops on 'Copying extracted folder /var/folders/pt/_mpbrdv90p3741h3xyt253pw0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1421713554555/phantomjs-1.9.8-macosx -> /Users/corbinu/Developer/tests/node_modules/phantomjs/lib/phantom'

I am on OS X 10.10

**Comment by pheuter** [comment]
Same.

**Comment by nicks** [comment]
i'm going to close this issue and re-open a different one, since it sounds like this is a new issue

**Comment by KenanSulayman** [comment]
given that io.js v1.0.1 is currently marked beta, I don't think we should try to work around this in this package (as it's a pretty far-reaching openssl problem)

err! The io.js versioning changed from what you're used to in node. It is not marked as beta, but as *unstable*, because it now follows the *Google Chrome release cycle*. We'll hit stable when V8 4.1 (Chrome 41) will hit mainstream.
