### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by rpbarron** [Medium/phantomjs#272]
Getting error below; on Windows 7; I see the files in the folder but they are zero bytes; did connecting to the Internet fail?

npm install -g rally-app-builder
\
> phantomjs@1.9.13 install C:\Users\barronr\AppData\Roaming\npm\node_modules\ral
ly-app-builder\node_modules\grunt-contrib-jasmine\node_modules\grunt-lib-phantom
js\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\xxxxx\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.
zip
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! phantomjs@1.9.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.13 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "rally-app-builder"
npm ERR! cwd C:\Users\xxxxx
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by nicks** [comment]
this means your network request is timing out. See the troubleshooting guide.
https://github.com/Medium/phantomjs#troubleshooting
