### ISSUE TITLE
404 with NPM install

### ISSUE THREAD

**Issue by deanclkclk** [Medium/phantomjs#273]
Been getting this since last night when I run npm install for Phantomjs. Wasn't getting this before:

          > phantomjs@1.9.13 install /home/rof/src/bitbucket.org/jorge- sandoval/xxxxxxxx_web/target-grunt/node_modules/karma-phantomjs-  launcher/node_modules/phantomjs
      > node install.js

     PhantomJS detected, but wrong version 1.9.7 @   /home/rof/.phantomjs/bin/phantomjs.
     Downloading http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
     Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
     Receiving...

     Error requesting archive.
     Status: 404
     Request options: {
     "uri": "http://cnpmjs.org/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
     "encoding": null,
     "followRedirect": true,
     "headers": {},
     "strictSSL": true
     }
     Response headers: {
     "server": "nginx/1.4.6 (Ubuntu)",
     "date": "Thu, 15 Jan 2015 09:32:55 GMT",
     "content-type": "text/plain; charset=utf-8",
     "content-length": "9",
     "connection": "keep-alive",
     "vary": "Accept-Encoding",
     "x-response-time": "600"
      }
     Make sure your network and proxy settings are correct.

      If you continue to have issues, please report this full log at     https://github.com/Medium/phantomjs
     npm ERR! phantomjs@1.9.13 install: `node install.js`
     npm ERR! Exit status 1
      npm ERR!  
      npm ERR! Failed at the phantomjs@1.9.13 install script.
      npm ERR! This is most likely a problem with the phantomjs package,
      npm ERR! not with npm itself.
      npm ERR! Tell the author that this fails on your system:
      npm ERR!     node install.js
      npm ERR! You can get their info via:
      npm ERR!     npm owner ls phantomjs
      npm ERR! There is likely additional logging output above.

**Comment by nicks** [comment]
according to the log, you're network or proxy settings are misconfigured, and you can't reach the site that hosts the binary. The installer is expected to fail in this case.
