### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by aug-riedinger** [Medium/phantomjs#274]
I get this error when doing ` npm install --save-dev phantomjs`.

Under Ubuntu, I tried first `sudo apt-get install phantomjs` and retried but still got the same error.

Apparently I am not the same: http://stackoverflow.com/questions/24950714/npm-install-phantomjs-error-on-centos-6-2

```
$ node --version
v0.10.25

$ npm --version
2.2.0
```

**Comment by nicks** [comment]
Can you post the full log?

**Comment by aug-riedinger** [comment]
As from this question: http://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod
I did `npm cache clean` and it seems to work better now.
