### ISSUE TITLE
iojs: certificate not trusted

### ISSUE THREAD

**Issue by rixrix** [Medium/phantomjs#276]
here's the complete log
---
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/cg/rvqz6_d97q304tnwmld2n5080000gq/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
/
Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:895:36)
    at TLSSocket.emit (events.js:92:17)
    at TLSSocket._finishInit (_tls_wrap.js:438:8)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.0.1
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.12 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.12 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

My env
---
OSX Yosemite
ls -athl `which node`
lrwxr-xr-x  1 admin  staff     4B 16 Jan 09:34 /usr/local/bin/node -> iojs
node v1.0.1

ping me if you need more details

**Comment by nicks** [comment]
this is a bug in io.js, you need to upgrade to a newer version. dupe #271

**Comment by rixrix** [comment]
hey thanks quick reply, sorry was just trigger-happy to submit
