### ISSUE TITLE
adding fs-extra drops support for node v0.8

### ISSUE THREAD

**Issue by maxbeatty** [Medium/phantomjs#283]
[fs-extra uses `setImmediate`](https://github.com/jprichardson/node-fs-extra/blob/master/lib/_copy.js#L54) which looks to be introduced to Timers in v0.9. [grunt-lib-phantomjs is depending on ~1.9.0-1](https://github.com/gruntjs/grunt-lib-phantomjs/blob/master/package.json#L33). Would you consider making a minor or major version bump instead of the 1.9.15 patch?

**Comment by nicks** [comment]
@jprichardson can you comment on whether it will be reasonable to make fs-extra compatible with node 0.8? I don't know how widespread 0.8 is, or how reasonable it is to drop support for node 0.8.

We will not be doing a minor version bump, because it is important to us to track the phantomjs version.

**Comment by jprichardson** [comment]
I can fix this. Just a sec.

**Comment by jprichardson** [comment]
Although, Node v0.10 is about 2 years old. Is v0.8 support necessary? I'll make this patch if it is.

**Comment by jprichardson** [comment]
Fixed. No change should be needed on your end since it's published as version `0.16.1`. https://github.com/jprichardson/node-fs-extra/releases/tag/0.16.1

**Comment by nicks** [comment]
awesome, thanks!

I'm going to ask around about v0.8 support anyway because I'm curious to know. I was under the impression that it was not accepting security fixes anymore and so is basically unsupported, but I can't find any official confirmation of this, so maybe I dreamed this.

**Comment by maxbeatty** [comment]
Thanks for addressing this so quickly. Yes, 0.8 is old, and we're planning to upgrade (just not today).
