### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by jefflembeck** [Medium/phantomjs#288]
http://phantomjs.org/release-2.0.html

PhantomJS 2.0 was released last week. Any chance a new release is in the cards?

**Comment by nicks** [comment]
AFAIK, the phantomjs 2.0 release is not complete yet. We usually get a note from the phantomjs team when they're ready to roll new versions out more widely. For updates on the release process, see:
https://github.com/ariya/phantomjs/issues/12897

**Comment by jefflembeck** [comment]
Yeah, just saw that PR fail and why it did. Thank you!

**Comment by andrey-p** [comment]
It's officially out now. [Official website](http://phantomjs.org/) has it it ready to download.

**Comment by nicks** [comment]
We are still blocking on the release on linux binaries.

**Comment by nicks** [comment]
also, the current binaries appear to be completely busted on newer versions of OSX, though the discussion on this bug https://github.com/ariya/phantomjs/issues/12630 suggest that this will be fixed before 2.0 is blessed.

**Comment by andrey-p** [comment]
That makes sense. Thanks for keeping on top of this!

**Comment by macbre** [comment]
https://github.com/ariya/phantomjs/issues/12897 - Linux binaries are still missing

**Comment by nicks** [comment]
It looks like the PhantomJS team was not able to build working OSX and Linux binaries of version 2.0, and has decided to abandon them and try to fix this in 2.1.

Given that this package is supposed to be a platform-independent binary installer, this puts us in a difficult position. We can't release an NPM package that doesn't work. We will have to wait until 2.1. 

https://github.com/ariya/phantomjs/issues/12970

**Comment by kenips** [comment]
@nicks it's actually getting fixed in 2.0.1 not 2.1. See https://github.com/ariya/phantomjs/issues/12948 and https://github.com/ariya/phantomjs/issues/12902. So while it's sad that we don't get 2.0.0 goodness the wait won't be that long either :).

**Comment by kevin-smets** [comment]
Do you guys have any luck running the 2.0.0 on OSX (10.10.3)? When I run it, the output is simply this

```[1]    3432 killed```

Or any other process number... Any idea's?

**Comment by attila** [comment]
I installed phantomjs 2.0.0 via Homebrew and it works fine though I'm on OS X 10.10.2.

**Comment by kevin-smets** [comment]
Just installed via homebrew instead of using the standalone bin. The brew version works properly, the standalone does not appear to work at all. Thanks!

**Comment by jefflembeck** [comment]
I had success unpacking the downloadable binary with `upx -d` - per https://github.com/ariya/phantomjs/issues/12974

**Comment by phated** [comment]
Could travis' linux binary be used https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-76759322 ?

**Comment by stevenvachon** [comment]
Anything happening here?

**Comment by dtothefp** [comment]
@stevenvachon I have a fork that is working with 2.0 here https://github.com/dtothefp/phantomjs

**Comment by stevenvachon** [comment]
@dtothefp awesome, thanks!

**Comment by nicks** [comment]
I think we're still waiting on official binaries that work on more than one platform before we do an official npm release.

**Comment by 3rd-Eden** [comment]
The website already lists all static builds for 2.0; http://phantomjs.org/download.html

**Comment by nicks** [comment]
for those following along, it looks like there's been some recent progress on producing a statically linked binary on linux. yay! https://github.com/ariya/phantomjs/issues/12948

**Comment by itajaja** [comment]
still no progress?

**Comment by coltonbrugger** [comment]
Time for 2.0.1? 2.1? Anything?

**Comment by just-boris** [comment]
I have already installed proper phantomjs on my computer, but I see a message in console
```
> phantomjs@1.9.17 install /src/server/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js
PhantomJS detected, but wrong version 2.0.0 @ /usr/bin/phantomjs.
```
I don't want to deal with extra downloads. So I created a mock package which does nothing: https://github.com/just-boris/phantomjs
It works nicely with `karma-phantomjs-launcher` which requires this module as peer dependency. 
No I have the following `package.json`
```
"karma-phantomjs-launcher": "^0.2.0",
"phantomjs": "just-boris/phantomjs",
```
and I so happy to use newest phantom

**Comment by ngryman** [comment]
Bump, `2.0` finally introduces `Function#bind` :v:

**Comment by nicks** [comment]
gee, imagine how far along phantomjs would be if people spent as much energy contributing upstream as they spent whining!

**Comment by piuccio** [comment]
@nicks I generally agree, but honestly phantomjs 2 was released too early. I still don't get the rationale of releasing a new version that works only on 1/3 of the platforms.

There was no rush to release it. They should have waited a bit longer.

**Comment by lekoaf** [comment]
Like @ngryman, I'd also like the new PhantomJs for the Function.bind() reason in my project. Does anyone have a timeline on this? Thank you!

**Comment by Lochlan** [comment]
@ngryman @lekoaf just use [a polyfill for Function.prototype.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill).  Add it to your actual project or load it only in your test runner, whatever makes sense for you.

**Comment by MarkLeMerise** [comment]
PhantomJS 2 also fixes an issue with `getOwnPropertyNames`. I assumed the `v2.0.0-alpha` tag would point to PhantomJS2 but it still seems to download 1.9.8.

**Comment by Lochlan** [comment]
@MarkLeMerise is using polyfills more cumbersome than hacking together phantomjs 2 support as an npm dependency?  I think the answer is definitely "no"--I would use polyfills (and I did, previously) but I need v2 to support the [webdriverio](https://github.com/webdriverio/webdriverio) 3 wdio test runner.

If you're like me and only need to support OS X and Ubuntu 14.04 binaries, and also need to use the "phantomjs" naming for peer dependencies to function correctly (unlike [this project](https://github.com/zeevl/phantomjs2)) I have [a fork that will work for you](https://github.com/Lochlan/phantomjs2), just use
```
"phantomjs": "git://github.com/Lochlan/phantomjs2.git#add3fd24dad48c0c4b2fe4d336442efea30e5f61",
```
in your package.json file.  If you need travis support you can just [add a few lines](https://github.com/Lochlan/LochlanMcIntosh.com/blob/04039fa8f8bcb76443c65f84967163a0e24f1bfa/.travis.yml#L7-L10) to your config, the key here is to make sure that the npm installer finds phantomjs "2.0.0" already installed.

As far as I can tell, forking this project seems to be the best solution for now.

**Comment by MarkLeMerise** [comment]
@Lochlan, I was about to update my comment to say that the "2.0.0-alpha" release of this package was working for me on OSX, but I use Jenkins as my CI env so I'll update with my findings.

**Comment by ngryman** [comment]
@Lochlan Yes I do use polyfills. It just feels awkward to use polyfills **only** for `phantomjs` and that you don't even need in production code (i.e. `Function.bind` is `ie8`).

**Comment by skysteve** [comment]
@ngryman not sure if you're able to, but I switched over to slimer JS (https://slimerjs.org/) because I wanted to use some ES6 features without having to pollyfill them. (As far as I know, anything that works in Firefox should work in slimer too).

(Sorry to post a "rival" "product" in here but lets be honest, phantom 2 was released too early and taking too long to address it's issues)

**Comment by ngryman** [comment]
@skysteve Thanks, will look into it :)

On a side note, this is nothing against `phantomjs`, I use it since its early release and it's a great tool!
It's not about *whining* neither (/ref @nicks).
It's about giving a perfectly valid feedback of a *user*, not a *contributor*, that needs this tool to evolve among our crazy Web ecosystem.

**Comment by rgbkrk** [comment]
How about now?

**Comment by Lochlan** [comment]
"How about now?" Has something changed recently that makes a difference with this issue?

**Comment by robertbaker** [comment]
PhantomJS 2 has a windows binaries available.

**Comment by stevenvachon** [comment]
Update?

**Comment by jontroncoso** [comment]
I saw on [the Downloads page](http://phantomjs.org/download.html) it referenceing [This Issue](https://github.com/ariya/phantomjs/issues/12948). On that ticket, it seams they are hard at work. So, hopefully They get past this roadblock soon. But also, if you check out [the second to last comment](https://github.com/ariya/phantomjs/issues/12948#issuecomment-145104606) it seams they are tired of people asking for updates.

Anyway, to the dev team thanks a lot for doing this! My experience with Phantomjs2 has been loads better so far! I almost want to donate some money to you...








...but I'm a cheapskate.

**Comment by kolesnik** [comment]
upgrade?

**Comment by brunowego** [comment]
+1

**Comment by tregusti** [comment]
@Lochlan What is the reason not supporting windows in your fork? Installation fails quite hard.

**Comment by flesler** [comment]
I see there's a `v2.0.0-alpha` tag in here, will it download PhantomJS 2 if I `npm install phantomjs@2.0.0-alpha` ?
Thanks, hope this can be solved soon

**Comment by just-boris** [comment]
@flesler nope. This tag was failed experiment. If you really want to use 2.0 version, just try another package, like: https://www.npmjs.com/package/phantomjs2 https://www.npmjs.com/package/phantomjs2.0 and others

**Comment by Lochlan** [comment]
@tregusti The reason I don't support Windows in my fork is that I don't have to support Windows machines, either at work or in my personal life.  If you would like to add Windows support and open a pull request I will be happy to accept it, or you are of course free to make your own fork as well.

**Comment by darrrk** [comment]
:+1:

**Comment by Vanuan** [comment]
New tracking issue: ariya/phantomjs#13822

**Comment by mikesherov** [comment]
@lochlan now that 64 bit binaries are out, and 32 bit binaries are just around the corner, can we expect phantomjs 2.0 support soon?

**Comment by Vanuan** [comment]
@mikesherov unfortunately, they are not out yet. They've just found a way to produce them on a sufficiently performant machine.

**Comment by mbrevda** [comment]
It seems the following was released. Is that what this issue has been waiting for?
```
phantomjs-2.1.0-linux-i686.tar.bz2
phantomjs-2.1.0-linux-x86_64.tar.bz2
phantomjs-2.1.0-macosx.zip
```

https://bitbucket.org/ariya/phantomjs/downloads

**Comment by Vanuan** [comment]
yay!

**Comment by mikesherov** [comment]
Still no 32-bit version though?

**Comment by Vanuan** [comment]
@mikesherov phantomjs-2.1.0-linux-i686.tar.bz2

**Comment by mbrevda** [comment]
PhantomJS 2.1is official:
https://groups.google.com/forum/m/#!msg/phantomjs/Jp4sDXrfmNg/I5J5TBFBDQAJ

**Comment by stevenvachon** [comment]
+1000

**Comment by MarkLeMerise** [comment]
Just tested this on Mac OS 10.11.2 and Windows 10 and it works great :smile: The long wait is over! Thanks!

**Comment by jdalton** [comment]
So what's the guidence on the npm package. I see the deprecation message for the `phantomjs` one but there's no official alternative.

**Comment by mbrevda** [comment]
phantomjs-prebuilt. Its in the readme!

**Comment by jdalton** [comment]
That's the medium package, no? I'm looking for the official one.

**Comment by mbrevda** [comment]
IDK if there is one, but that would be interesting

**Comment by mikesherov** [comment]
Both `phantomjs` and `phantomjs-prebuilt` are the same package, both maintained by medium. There is no official node installer maintained by the phantomjs team. Simply update `phantomjs` to `phantomjs-prebuilt` in your package.json.
