### ISSUE TITLE
I am behind a proxy that uses self-signed SSL certificates and requests should work

### ISSUE THREAD

**Issue by deployable** [Medium/phantomjs#293]
I have a custom certificate that does work for all other `npm` operations but the phantomjs download hits the documented error message. I saw the note in the readme about turning off ssl verification but that's not really a valid fix. 

`npm` supports a custom CA file so the phantom installer should be able to as well. 

    $ cat ~/.npmrc
    cafile=/path/to/blah.pem

Add support for passing `cafile` through to `request`

**Comment by nicks** [comment]
this should be fixed in #296
