### ISSUE TITLE
module.js:340 error in install

### ISSUE THREAD

**Issue by chaim1221** [Medium/phantomjs#301]
Yo. Windows 8.1x64 with Node 0.12.0 stable.

Trying to install phantomjs for use by karma. Started with `npm install -g karma-phantomjs-launcher` and it threw. For some reason it's looking for install.js in my documents folder. So I tried a good old `npm install -g phantomjs` and it throws the same error. Looking at the other stuff on here, I figured it's best if I give the verbose log, so here is the relevant portion:

(snip)
npm info install request@2.42.0
npm info postinstall request@2.42.0
npm verb unlock done using C:\Users\celiyah\AppData\Roaming\npm-cache\_locks\request-7c0e9278fd22550
4.lock for C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs\node_modules\request
npm verb about to build C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs
npm info build C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs
npm verb linkStuff [ true,
npm verb linkStuff   'C:\\Users\\celiyah\\AppData\\Roaming\\npm\\node_modules',
npm verb linkStuff   true,
npm verb linkStuff   'C:\\Users\\celiyah\\AppData\\Roaming\\npm\\node_modules' ]
npm info linkStuff phantomjs@1.9.15
npm verb linkBins phantomjs@1.9.15
npm verb link bins [ { phantomjs: './bin/phantomjs' },
npm verb link bins   'C:\\Users\\celiyah\\AppData\\Roaming\\npm',
npm verb link bins   true ]
npm verb linkMans phantomjs@1.9.15
npm verb rebuildBundles phantomjs@1.9.15
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'adm-zip',
npm verb rebuildBundles   'fs-extra',
npm verb rebuildBundles   'kew',
npm verb rebuildBundles   'npmconf',
npm verb rebuildBundles   'progress',
npm verb rebuildBundles   'request',
npm verb rebuildBundles   'request-progress',
npm verb rebuildBundles   'which' ]
C:\Users\celiyah\AppData\Roaming\npm\phantomjs -> C:\Users\celiyah\AppData\Roaming\npm\node_modules\
phantomjs\bin\phantomjs
npm info install phantomjs@1.9.15

> phantomjs@1.9.15 install C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs
> node install.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\celiyah\Documents\install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm verb unsafe-perm in lifecycle true
npm info phantomjs@1.9.15 Failed to exec install script
npm verb unlock done using C:\Users\celiyah\AppData\Roaming\npm-cache\_locks\phantomjs-6339908fd728e
438.lock for C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs
npm verb stack Error: phantomjs@1.9.15 install: `node install.js`
npm verb stack Exit status 8
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\l
ifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\s
pawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1008:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
npm verb pkgid phantomjs@1.9.15
npm verb cwd C:\
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "install" "-g" "phantomjs" "--verbose"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the phantomjs@1.9.15 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules\phantomjs
npm info preuninstall phantomjs@1.9.15
npm info uninstall phantomjs@1.9.15
npm verb unbuild rmStuff phantomjs@1.9.15 from C:\Users\celiyah\AppData\Roaming\npm\node_modules
npm verb gentlyRm verifying that C:\Users\celiyah\AppData\Roaming\npm is managed by npm
npm verb gentlyRm vacuuming C:\Users\celiyah\AppData\Roaming\npm\phantomjs.cmd up to C:\Users\celiya
h\AppData\Roaming\npm
npm verb gentlyRm verifying that C:\Users\celiyah\AppData\Roaming\npm is managed by npm
npm verb gentlyRm vacuuming C:\Users\celiyah\AppData\Roaming\npm\phantomjs up to C:\Users\celiyah\Ap
pData\Roaming\npm
npm info postuninstall phantomjs@1.9.15
npm verb gentlyRm vacuuming C:\Users\celiyah\AppData\Roaming\npm\node_modules\phantomjs

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>

**Comment by nicks** [comment]
this seems like an NPM bug. It's not even reaching the phantom installer.

**Comment by chaim1221** [comment]
Yeah, I saw that in the related thread. But I also tried on 0.10.29 with same result. FWIW, npm seems to think it's a phantomjs bug. ;)

**Comment by nicks** [comment]
that's just the default npm message. If you'd like, we can print an error message saying it's an npm bug.

**Comment by chaim1221** [comment]
Word. Well thanks for looking anyway.
