### ISSUE TITLE
Unalbe to install from source

### ISSUE THREAD

**Issue by realtebo** [Medium/phantomjs#303]
Steps:

    git clone https://github.com/Medium/phantomjs.git
    cd phantomjs/
    git checkout v1.9.15
    npm install phantomjs

Error:
    
    npm WARN install Refusing to install phantomjs as a dependency of itself

What?

**Comment by nicks** [comment]
The NPM error message is correct: you can't install phantomjs as a dependency of phantomjs; that doesn't make sense.

**Comment by realtebo** [comment]
@nicks I know that error message is correct, but I'm just trying to do a 'npm install phantomJs -g', I'm not doing nothing else. 

So the npm package config is wrong, I suppose.
