### ISSUE TITLE
Cannot start PhantomJS Error: spawn EACCES from Jenkins project 

### ISSUE THREAD

**Issue by deva-tm** [Medium/phantomjs#305]
We are trying to run a Jenkins project on Linux. In that project unit test cases have to be executed on the Javascript code by a grunt task. For executing unit test cases we are using grunt-karma(0.4.6), karma-phantomjs-launcher(0.1.4) and phantomjs(1.9.7) module. When the grunt task is executed through the jenkins project shell script plugin we are getting the following error messages.

[4mRunning "karma:continuous" (karma) task[24m
[32mINFO [karma]: [39mKarma server started at http://localhost:9058/
[32mINFO [launcher]: [39mStarting browser PhantomJS
[32mINFO [launcher]: [39mCreating temp dir at /tmp/testacular-93143418
[32mINFO [launcher]: [39mProcess PhantomJS exitted with code -1
[31mERROR [launcher]: [39mCannot start PhantomJS
Error: spawn EACCES

[32mINFO [launcher]: [39mTrying to start PhantomJS again.
[32mINFO [launcher]: [39mCreating temp dir at /tmp/testacular-93143418
[32mINFO [launcher]: [39mProcess PhantomJS exitted with code -1
[31mERROR [launcher]: [39mCannot start PhantomJS
Error: spawn EACCES
[[32mINFO [launcher]: [39mTrying to start PhantomJS again.
[32mINFO [launcher]: [39mCreating temp dir at /tmp/testacular-93143418
[32mINFO [launcher]: [39mProcess PhantomJS exitted with code -1
[31mERROR [launcher]: [39mCannot start PhantomJS
Error: spawn EACCES

[33mWarning: Task "karma:continuous" failed. Use --force to continue.[39m

Note:: The project and the grunt test task runs successfully on Windows 7 without any errors.The version of all the npm modules is also the same.

**Comment by nicks** [comment]
EACCES typically means you lost permission to read or execute things from that directory. is your grunt task trying to run in a directory that jenkins doesn't give it access to?

**Comment by deva-techMahindra** [comment]
Grunt tasks are executing in "node modules" directory inside a Jenkins Project. We have provided all the permissions to all the files and directories inside the Jenkins installation directory. So i do not think that it might be an issue

**Comment by nicks** [comment]
hmmm...not sure. Because no one else is seeing this, and the error is about permissions in your environment, I don't think there's much we can do to help you debug this. Let us know if there's something in particular you'd like us to change.

**Comment by yanlijun** [comment]
D:\grunttest>npm install
/


> phantomjs@1.9.16 install D:\grunttest\node_modules\grunt-contrib-qunit\node_mo
dules\grunt-lib-phantomjs\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\ZHANGX~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...
-
Error making request.
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN engine xmlbuilder@2.4.6: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  ||
 1.0.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\grunttest\npm-debug.log

**Comment by nicks** [comment]
Closing this, as this appears to be a problem with permissions in your environment, and there's not much we can do about that.

**Comment by L-Dogg** [comment]
@nicks is right, it is problem with your environment setup. I also had this problem, but I'm running my Jenkins tests with Firefox on CentOS and setting right FIREFOX_BIN system variable solved it.

**Comment by mahamuniraviraj** [comment]
I faced similar error. Developers are using windows platform and  Jenkins is on linux platform. npm package Phantomjs is platform dependent. If your node_modules are under version control, you endup in running different platform's phantomjs, which causes Error: spawn EACCES. Simple solution is remove phantomjs dev dependency from package.json. Independently "npm install phantomjs" on each machine.

**Comment by shusain** [comment]
Similar to @L-Dogg has this problem with a jenkins build but was because I had a bad path for my PHANTOMJS_BIN was getting the errors when karma was running and trying to launch phantom, would be nice if there was some more error handling around this in the karma phantom plugin I guess not a problem with phantomjs itself though.

**Comment by nDrju826** [comment]
For me it helped to simply remove PHANTOMJS_BIN property. My test Jenkins server is located on the same host as the git repository.

**Comment by naveen-yadav** [comment]
@mahamuniraviraj 
tried your approach but still getting the same issue.

error msg:

```
[31m01 06 2018 07:24:58.202:ERROR [launcher]: [39mCannot start PhantomJS
	Auto configuration failed
140437220120352:error:0200100D:system library:fopen:Permission denied:bss_file.c:169:fopen('/etc/ssl/openssl.cnf','rb')
140437220120352:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:174:
140437220120352:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:199:
```

**Comment by shusain** [comment]
@naveen-yadev https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=584911 looks like just missing openssl install on the target machine.

**Comment by naveen-yadav** [comment]
thanks shusain, that was helpful. But I am not authorized to install openssl or get permission for it. So is there any workaround through which I can skip openssl call and launch my PhantomJS browser.

**Comment by shusain** [comment]
@naveen-yadav just FYI I may have jumped to a conclusion there would double check if the file exists if not then likely missing the openssl package installation.  I don't think there's a way to use PhantomJS without openssl installed though looks like it depends on it for any of the HTTPS/ssl certificates or ciphers http://phantomjs.org/api/command-line.html (search openssl)
