### ISSUE TITLE
jQuery page.includeJs writes CORS error to stdout

### ISSUE THREAD

**Issue by gregl83** [Medium/phantomjs#309]
Using page.includeJs function writes an error to stdout making it difficult to parse a response from phatomjs.

Example:
```javascript
page.includeJs("//code.jquery.com/jquery-1.9.0.min.js", function() {
```

Error:
```bash
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///home/ubuntu/phantom.js. Domains, protocols and ports must match.
```
**Larger Issue**
Errors and other text can/is written to stdout while it's also being used in this module to get results from phantomjs.  This leads to very inconsistent results.

**Comment by gregl83** [comment]
Looks like another similar library had this issue:
[ariya/phantomjs issue 12697](https://github.com/ariya/phantomjs/issues/12697)

I'm solving my problem for now using this method:
```javascript
setTimeout(function(){
  phantom.exit()
}, 0);
```

**Comment by nicks** [comment]
Sorry, this repo is just an NPM installer. Yes, https://github.com/ariya/phantomjs is the repo of the phantomjs project, and that issue is the problem you're having.

**Comment by gregl83** [comment]
Feature request? :8ball:
