### ISSUE TITLE
Installing from npm grabs the wrong version

### ISSUE THREAD

**Issue by chevdor** [Medium/phantomjs#311]
Hello,

trying to install 1.9.16, npm grabs 1.9.8 on osx.

```
> phantomjs@1.9.16 install /usr/local/lib/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/ff/pqx4w8zx5yd73j2vq4004r4c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
```

I tried removing the cached version without success, it keeps on grabbing 1.9.8.

**Comment by nicks** [comment]
this is correct behavior, the patch number does not correspond to the phantomjs patch number. see
https://github.com/Medium/phantomjs#versioning
