### ISSUE TITLE
How to list the resources that were loaded (CSS, JS, images etc)?

### ISSUE THREAD

**Issue by IonicaBizau** [Medium/phantomjs#312]
How to list the resources that were loaded (including CSS, JS, image files etc)?

**Comment by nicks** [comment]
Sorry, this project is just an NPM installer for phantomjs, not the main project. This is probably a good question for the phantomjs mailing list.
https://groups.google.com/forum/#!forum/phantomjs

**Comment by IonicaBizau** [comment]
I opened [this topic](https://groups.google.com/forum/#!topic/phantomjs/thYrajJ2Cgc), but nobody answered... :disappointed:

Maybe @JamesMGreene could give a good point there. Thanks!
