### ISSUE TITLE
install spm

### ISSUE THREAD

**Issue by wuchangming** [Medium/phantomjs#313]
Error making request.
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

Please report this full log at https://github.com/Medium/phantomjs

**Comment by nicks** [comment]
this usually indicates a problem with your network. Try the FAQ for troubleshooting steps:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
