### ISSUE TITLE
Error extracting zip

### ISSUE THREAD

**Issue by hongcai** [Medium/phantomjs#315]
npm install phantomjs fail on my window 7,  npm(1.4.28), node(0.10.35)

> Extracting zip contents
> Error extracting zip
> Phantom installation failed Invalid or unsupported zip format. No END header fou
> nd undefined
> 
> npm verb unsafe-perm in lifecycle true
> npm info phantomjs@1.9.16 Failed to exec install script
> npm ERR! phantomjs@1.9.16 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the phantomjs@1.9.16 install script.
> npm ERR! This is most likely a problem with the phantomjs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls phantomjs
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.1.7601
> npm ERR! command "D:\\application\\nodejs\\\\node.exe" "D:\\application\\nodejs\
> \node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs" "-g" "--verbose" "--p
> hantomjs_cdnurl=http://cnpmjs.org/downloads"
> npm ERR! cwd D:\application\npm\node_modules
> npm ERR! node -v v0.10.35
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm verb exit [ 1, true ]
> npm verb node_modules\phantomjs unbuild
> npm info preuninstall phantomjs@1.9.16
> npm info uninstall phantomjs@1.9.16
> npm verb true,D:\application\npm\node_modules,D:\application\npm\node_modules un
> build phantomjs@1.9.16
> npm verb D:\application\npm,[object Object] binRoot
> npm info postuninstall phantomjs@1.9.16
> npm ERR! not ok code 0

**Comment by nicks** [comment]
can you include the full log?

if you download the zip manually, are you able to open it successfully?

**Comment by hongcai** [comment]
yep. the zip file downloaded could not open properly.
I find a turn around:
> D:\application\npm\node_modules>npm install -g D:\tools\phantomjs-1.9.16.tar --v
erbose

and make it through now:
>D:\application\npm\node_modules>npm list phantomjs
>D:\application\npm
>└── phantomjs@1.9.16
