### ISSUE TITLE
Phantomjs failed on Windows 20012 Server

### ISSUE THREAD

**Issue by adriatic** [Medium/phantomjs#318]
I was trying to create the Stormpath application using the https://docs.stormpath.com/angularjs/guide/ as my guide. Specifically in the step 
```
yo angular-fullstack dashboard-app
```
Yeoman reported the error:
```
Please report this full log at https://github.com/Medium/phantomjs
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Work\Learning\Stormpath
npm ERR! node -v v0.10.30
npm ERR! npm -v 2.0.0-alpha-5
npm ERR! code ELIFECYCLE
```

I have the complete log saved for your convenience

**Comment by nicks** [comment]
can you post the full log?

**Comment by adriatic** [comment]
I would be delighted to - if you tell me how, as I only know how to upload images :-(

**Comment by adriatic** [comment]
Please use Please use the document at https://github.com/congral/Issue-support-evidence/commit/d067dfdb3d56d6aad23f869e4407fead392fb882

**Comment by nicks** [comment]
you need to install node on PATH

**Comment by adriatic** [comment]
Very cryptic answer, leading me to ask: Do you mean that the reference to the folder where node lives has to be defined on the PATH system environment variable? If so, your diagnosis does not solve my problem as I already have "c:\nodejs" on my PATH variable. 
Can you please explain?

**Comment by nicks** [comment]
The error message says it was not able to run 'node'

**Comment by adriatic** [comment]
You are correct and I stand corrected: node was not installed via Windows installer but rather just unzipped in a folder. While node worked for my need, this setup was incorrect. Once I correct this problem, phantom was installed (as a part of this looong `yo angular-fullstack dashboard-app` correctly.

Thank you for helping me with this - even when the problem was mine. I will also report this resolution to the Stormpath support as they were my first victim :-)

**Comment by adriatic** [comment]
You are correct and I stand corrected: node was not installed via Windows installer but rather just unzipped in a folder. While node worked for my need, this setup was incorrect. Once I addressed this problem, phantom was installed (as a part of this looong `yo angular-fullstack dashboard-app` without a hitch..

Thank you for helping me with this - even when the problem was mine. I will also report this resolution to the Stormpath support as they were my first victim :-)
