### ISSUE TITLE
phantomjs@1.9.16  is breaking grunt-mocha install

### ISSUE THREAD

**Issue by tarunbatta** [Medium/phantomjs#320]
D:\Data\Code\AvMET4>npm install grunt-mocha --save-dev
/
> phantomjs@1.9.16 install D:\Data\Code\AvMET4\node_modules\grunt-mocha\node_modules\grunt-lib-phantomjs\node_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'D:\Data\Code\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-mocha" "--save-dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Data\Code\AvMET4\npm-debug.log

D:\Data\Code\AvMET4>npm owner ls phantomjs
dpup <dan@pupi.us>
nicks <nicholas.j.santos@gmail.com>
medium <npm@medium.com>

D:\Data\Code\AvMET4>

**Comment by nicks** [comment]
dupe #302
