### ISSUE TITLE
Issue encountered when using Yeoman

### ISSUE THREAD

**Issue by damiangonzalez** [Medium/phantomjs#324]
> phantomjs@1.9.16 install C:\Projects\DddMeanMqClient\dddmeanmq\node_modules\ka
rma-phantomjs-launcher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\damiango\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...

Error making request.
Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO
:unknown protocol:openssl\ssl\s23_clnt.c:782:

    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:766:14)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Projects\\DddMeanMqClient\\\\node.exe" "C:\\Projects\\DddMean
MqClient\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\DddMeanMqClient\dddmeanmq\npm-debug.log

C:\Projects\DddMeanMqClient\dddmeanmq>

**Comment by nicks** [comment]
this error means the ssl handshake failed. Are you behind some network proxy that's trying to intercept your traffic and botching it?

**Comment by nicks** [comment]
closing this without further repro steps.

**Comment by nasihere** [comment]
If you are using windows corporate laptop or desktop. problem is because of firewall or access denied.

use this

npm config set registry http://registry.npmjs.org/
so that npm requests for http url instead of https.

and then try the same npm install command

**Comment by MatthewRalston** [comment]
In my case, the bitbucket url for phantomjs was requested via https, and npm correctly attempted to use my https proxy, but the request still failed. Not sure what is going on there. The solution for me was to download the requested phantomjs.tar.bz2 into the tmp location specified by npm. Then npm was able to extract and install this dependency.
