### ISSUE TITLE
Self signed certificate in chain

### ISSUE THREAD

**Issue by blemaire** [Medium/phantomjs#336]
Hi I am trying to install phantomjs via npm but get the following errors:

> npm install phantomjs
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN package.json karma-mocha@0.1.10 No README data
/
> phantomjs@1.9.16 install C:\prog\node\AngularJS-Testing-Article\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\xxx\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "phantomjs"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\prog\node\xxx\npm-debug.log

**Comment by nicks** [comment]
this FAQ item should explain the problem, let us know if it's not clear!
https://github.com/Medium/phantomjs#i-am-behind-a-corporate-proxy-that-uses-self-signed-ssl-certificates-to-intercept-encrypted-traffic

**Comment by eerlikh** [comment]
How is this issue closed? How was it resolved?
