### ISSUE TITLE
npmbox for phantomjs

### ISSUE THREAD

**Issue by naveenbirru** [Medium/phantomjs#339]
I am facing an issue where I am using npmbox to install phantomjs. And it seems like npm install process for phantomjs executes an install script that goes out to a CDN to fetch the latest version of phantomjs and stores it on its own. npmbox doesn't know anything about this cdn or the file retrieved from it. When you go to npmunbox phantomjs later, it's still going to make a network connection and try and get the cdn file. 

Please let me know if there is any solution/workaround to use phanthomjs along with npmbox?

**Comment by nicks** [comment]
yes, you can just install phantomjs separately on the box, see
https://github.com/Medium/phantomjs#using-phantomjs-from-disk
