### ISSUE TITLE
Failed at the phantomjs@1.9.17 install script 'node install.js'.

### ISSUE THREAD

**Issue by polinac** [Medium/phantomjs#344]
I run 'npm instal'l for https://github.com/linnovate/mean.git. I have Windows 8.1. I got error:

------
Failed at the phantomjs@1.9.17 install script 'node install.js'.
This is most likely a problem with the phantomjs package,
not with npm itself.
------

I can upload npm-debug.log where you can accept it.
Can you please help me to resolve this?
![capture](https://cloud.githubusercontent.com/assets/12117128/7779940/223dd7f8-008e-11e5-9b28-b9e91d315a0b.PNG)

**Comment by tomatau** [comment]
same error on jenkins

**Comment by nicks** [comment]
this report does not include any meaningful logs or repro steps. if you want us to look into this, you'll have to include the logs.

**Comment by polinac** [comment]
Hm. Something changed in the opensource world. I just run npm install again and it completed without errors.

**Comment by nicks** [comment]
probably a transient network error

**Comment by polinac** [comment]
Anyway, thank you for looking into this.

**Comment by middle8media** [comment]
I am still having this error every time I run `npm install`

**Comment by nicks** [comment]
@middle8media https://github.com/Medium/phantomjs#i-am-behind-a-corporate-proxy-that-uses-self-signed-ssl-certificates-to-intercept-encrypted-traffic

**Comment by middle8media** [comment]
tried `npm set strict-ssl false`

but ...

```
> phantomjs@1.9.17 install /Users/M8M/Sites/rollcall-pattern-library/node_modules/gulp-iconify/node_modules/gulp-svg2png/node_modules/svg2png/node_modules/phantomjs
> node install.js

PhantomJS detected, but wrong version 1.9.1 @ /opt/boxen/nodenv/versions/v0.10.5/bin/phantomjs.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/81/jglkvkm16jdcw9494_lkvpr40000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Using npmconf ca
Receiving...

Error making request.
Error: 140735117423360:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:703:Expecting: CERTIFICATE

    at SlabBuffer.use (tls.js:232:18)
    at CleartextStream.read [as _read] (tls.js:417:29)
    at CleartextStream.Readable.read (_stream_readable.js:304:10)
    at tls.js:475:12
    at process._tickCallback (node.js:415:13)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/opt/boxen/nodenv/versions/v0.10.5/bin/npm" "install"
npm ERR! node v0.10.5
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/M8M/Sites/rollcall-pattern-library/npm-debug.log
```

**Comment by nicks** [comment]
It looks like you have the CA settings in your npmconf misconfigured.

**Comment by middle8media** [comment]
I am unfamiliar with that, looking into it.

The weird thing is that I have been developing and running `npm install` in this directory for a while. My co-worker added some gulp packages and I ran `npm install` to bring my local directory up to date, then ran into these problems. Wondering why?

**Comment by middle8media** [comment]
any specific guidance would be appreciated.

**Comment by middle8media** [comment]
I am unsure of where the npmconf file is and unsure of what CA settings to add.

**Comment by sraghavendra** [comment]
Got the same error while installing the phantomjs on node version 10.x

I upgraded to latest node and it is working fine now :)

**Comment by NioTeX** [comment]
Was getting same error, updated to latest nodejs, and everything works now:
```bash
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by patrickmichalina** [comment]
:+1: this blows up in azure...

Phantom installation failed { [Error: ENOENT, open 'D:\home\site\repository\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs\lib\phantom\ChangeLog']
  errno: -4058,
  code: 'ENOENT',
  path: 'D:\\home\\site\\repository\\node_modules\\gulp-uncss\\node_modules\\uncss\\node_modules\\phridge\\node_modules\\phantomjs\\lib\\phantom\\ChangeLog' } Error: ENOENT, open 'D:\home\site\repository\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs\lib\phantom\ChangeLog'
    at Error (native)
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "D:\\Program Files (x86)\\npm\\2.7.4\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

**Comment by nicks** [comment]
@patrickmichalina ENOENT usually means that you do not have `node` installed on PATH. See https://github.com/Medium/phantomjs#installation-fails-with-spawn-enoent

**Comment by nicks** [comment]
I'm locking this issue, because it is becoming a dumping ground for lost souls complaining about unrelated issues.
