### ISSUE TITLE
install.js fails to download the binaries if the server does not send a Content-Length header

### ISSUE THREAD

**Issue by strohmattenverleger** [Medium/phantomjs#347]
If the install.js script is downloading the binaries from a server which does not send a Content-Length header, the script fails because it cannot render the progress bar.

See [install.js:298](https://github.com/Medium/phantomjs/blob/91f999d88d6f9328b9f1e71eb5bc743695ab60b5/install.js#L298) for details. Here the script tries to instantiate a progress bar passing in "state.total" which can be null.
This is also documented [here](https://github.com/IndigoUnited/node-request-progress/tree/0.3.1).
> The properties bellow can be null if response does not contain the content-length header

**Comment by nicks** [comment]
this seems like a non-issue, because the CDN does send a content-length header? but i guess we'd accept a PR for this.

**Comment by strohmattenverleger** [comment]
Yes, the default CDN does send a Content-Length header, so no issue here. What I was trying to say was, that in situations where one would override the CDN URL due to company policies and the internal CDN does not send such a header, the download will fail.

**Comment by nicks** [comment]
i think this is fixed now
