### ISSUE TITLE
Problem explicitly installing 1.9.8

### ISSUE THREAD

**Issue by brianroesler** [Medium/phantomjs#348]
When I install 1.9.8 explicitly on Linux (npm install -g phantomjs@1.9.8), it installs 1.9.7 instead.

**Comment by nicks** [comment]
working as intended, see https://github.com/Medium/phantomjs#versioning

**Comment by brianroesler** [comment]
You should probably have the current working version as an explicit option now so you don't break people's code who need 1.9.8 whenever you update (e.g. whenever you do jump to 2.0 everyone using spookyjs will break).

**Comment by nicks** [comment]
in semver, it's considered best practice to fix on a particular major/minor
version, but _not_ to fix on a particular patch version. This post has a
good explanation, particularly the part about "The Case for Semver Ranges"
https://nodesource.com/blog/semver-a-primer
