### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by middle8media** [Medium/phantomjs#349]
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/opt/boxen/nodenv/versions/v0.10.5/bin/npm" "install"
npm ERR! node v0.10.5
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/M8M/Sites/rollcall-pattern-library/npm-debug.log

**Comment by HintikkaKimmo** [comment]
Getting the same error as well.

**Comment by nicks** [comment]
it's sad that you decided to remove all the useful logs in this bug report, as opposed to your post in the other bug.

as described in the other bug, this is a problem with your CA settings. If you're not familiar with your CA settings, it's likely you will need to get your local network admin to help you. There's not much we can do to help you with this.

**Comment by nicholasstark** [comment]
I'm seeing the same issue.

c:\Dev\repos\manage\isp\web>npm start

> web@1.0.0 prestart c:\Dev\repos\manage\isp\web
> npm install && grunt i18n


> phantomjs@1.9.17 install c:\Dev\repos\manage\isp\web\node_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Dev\repos\manage\isp\web\node_modules\phantomjs\install.js:9:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Dev\\nodejs\\\\node.exe" "C:\Dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Dev\repos\manage\isp\web\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Dev\\nodejs\\\\node.exe" "C:\\Dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! web@1.0.0 prestart: `npm install && grunt i18n`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@1.0.0 prestart script 'npm install && grunt i18n'.
npm ERR! This is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && grunt i18n
npm ERR! You can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Dev\repos\manage\isp\web\npm-debug.log

c:\Dev\repos\manage\isp\web>
