### ISSUE TITLE
protractor with phantomjs: unable to run with manually installed phantomjs v2.0.x

### ISSUE THREAD

**Issue by janppires** [Medium/phantomjs#357]
Hi.

I need to run my protractor tests with phantomjs `v2.0.x`, because this version has a bug fixed somewhere that allows me to run successfully my tests on a remote jenkins machine.

But, I cannot understand the right way of setting up correctly my protractor/phantomjs or npm package.json file configuration to use the phantomjs v2.0.x.

In the middle of the process of running my protractor tests, I get this behavior:

> Starting process 'command 'npm''. Working directory: /home/jenkins/workspace/ballyhoo.branch.build.playground Command: npm install
> Successfully started process 'command 'npm''
npm WARN package.json ballyhooApp@ No repository field.

> phantomjs@1.9.17 install /home/jenkins/workspace/ballyhoo.branch.build.playground/node_modules/phantomjs
> node install.js

> PhantomJS detected, but wrong version 2.0.1-development @ /usr/bin/phantomjs.
> Download already available at /home/jenkins/tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
> Extracting tar contents (via spawned process)
> Removing /home/jenkins/workspace/ballyhoo.branch.build.playground/node_modules/phantomjs/lib/phantom
Copying extracted folder /home/jenkins/tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1435945592046/phantomjs-1.9.8-linux-x86_64 -> /home/jenkins/workspace/ballyhoo.branch.build.playground/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/jenkins/workspace/ballyhoo.branch.build.playground/node_modules/phantomjs/lib/phantom/bin/phantomjs

In my system, when I do `which phantomjs` I get `/usr/bin/phantomjs`, and this path belongs to my PATH:
> echo $PATH
>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Right now, the only way I know to get this working is to reconfigure my `protractor.conf.js` file to have:
>capabilities:{ 'browserName': 'phantomjs', phantomjs.binary.path':'/usr/bin/phantomjs'}

but I would like to avoid it.

Inside my local node_modules folder I have `phantomjs` installed, with `v1.9.17`. I believe that this version cames from a dependency of 'karma-phantomjs-launcher' that I need to have (unless there is other way to replace this).

So, how do I use protractor with my /usr/bin/phantomjs bin file, which is a 2.0.x version?

Thank you!

**Comment by nicks** [comment]
read this comment https://github.com/Medium/phantomjs/issues/288#issuecomment-110167730 on how to replace karma-phantomjs-launcher with your own package.
