### ISSUE TITLE
DalekJS npm install

### ISSUE THREAD

**Issue by cymbiotica** [Medium/phantomjs#359]
Here is the error: 
c:\projects\dalekjs>npm install dalekjs --save-dev
npm WARN package.json IRISTest1@0.0.1 No repository field.
npm WARN package.json IRISTest1@0.0.1 No README data
npm WARN engine node-pngjs@0.0.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.34","npm":"1.4.28"})
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'

> phantomjs@1.9.12 install c:\projects\dalekjs\node_modules\dalekjs\node_modules\dalek-browser-phantomjs\node_modules\ph
antomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to <user directory>\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! phantomjs@1.9.12 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.12 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "dalekjs" "--save-dev"
npm ERR! cwd c:\projects\dalekjs
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I have tried to run npm set ca null to no avail.

**Comment by cymbiotica** [comment]
Guess I can override this with 
npm config set strict-ssl false

**Comment by nicks** [comment]
ya, see
https://github.com/Medium/phantomjs#i-am-behind-a-corporate-proxy-that-uses-self-signed-ssl-certificates-to-intercept-encrypted-traffic
or
https://github.com/Medium/phantomjs#i-tried-everything-but-my-network-is-b0rked-what-do-i-do
