### ISSUE TITLE
npm install failed . 

### ISSUE THREAD

**Issue by huruxing159** [Medium/phantomjs#362]
I see that the it has been downloaded ,but  after uncompressed , the folder is empty.

> phantomjs@1.9.17 install C:\WebstormProjects\saratoga\mpp-ui\node_modules\karm
a-phantomjs-launcher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\hurux\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zi
p
Receiving...
|
Error making request.
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WebstormProjects\saratoga\mpp-ui\npm-debug.log

**Comment by nicks** [comment]
see the FAQ:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
https://github.com/Medium/phantomjs#i-tried-again-but-i-get-econnreset-or-etimedout-consistently
https://github.com/Medium/phantomjs#i-tried-everything-but-my-network-is-b0rked-what-do-i-do
