### ISSUE TITLE
Failed to install script

### ISSUE THREAD

**Issue by frozenamazon** [Medium/phantomjs#364]
Error making request.
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\PROGRA~1\\nodejs\\\\node.exe" "c:\\PROGRA~1\\nodejs\\node_
modules\\npm\\bin\\npm-cli.js" "install" "phantomjs"
npm ERR! cwd H:\Workspace\Dash\pfinder\PeopleFinder
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by nicks** [comment]
this usually indicates some network problem on your end, please read:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
https://github.com/Medium/phantomjs#i-tried-again-but-i-get-econnreset-or-etimedout-consistently
