### ISSUE TITLE
CentOS release 6.6 (Final) not matched with suitable PhantomJS binary

### ISSUE THREAD

**Issue by MarkLeMerise** [Medium/phantomjs#367]
I am attempting to use the `2.0.0-alpha` release and I think I am confused by some behavior in how it handles finding a suitable PhantomJS binary for CentOS release 6.6 (Final).

[This line of the install](https://github.com/Medium/phantomjs/blob/v2.0.0-alpha/install.js#L357) does a check to see if the string "amzn" can be found in the `os.release()`. On the system in question, this string is `2.6.32-504.23.4.el6.x86_64`, so it fails to find a suitable binary, and errors out.

Is this the expected behavior?

*As an aside, the error message instructs the user to build PhantomJS from source and add it to the PATH, which I have. Unfortunately, on CentOS, the version built is `2.0.1-development`, which causes a different, unrelated error in the install script.*

**Comment by nicks** [comment]
yes, 2.0.0-alpha was a crazy experiment that never worked. that's why it's alpha. i've unpublished it to prevent future people from wasting time on this. the unpublish will propagate in a few hours i think.

**Comment by MarkLeMerise** [comment]
Fair enough, I understand. I am just stuck in a pickle because there doesn't seem to be a 2.0.0 binary for CentOS, so I built from source, which now doesn't match the version specified in the `lib/phantomjs.js` file, which causes the entire `npm install` to fail. I just wanted to note here that I have forked to account for this discrepancy in case anyone runs into the same thing.

**Comment by just-boris** [comment]
I ran into the same thing. Now I have a fork of this package to use with provided phantomjs: https://github.com/just-boris/phantomjs
