### ISSUE TITLE
Error installing phantomJS:  phantomjs-1.9.8-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by benbracha** [Medium/phantomjs#368]
It seems like the service is unavailable (trying to access the link directly).
Any known issue / recommended workaround (are there available CDNs for this?)

```
Error requesting archive.
Status: 503
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "date": "Mon, 10 Aug 15 09:46:29 GMT",
  "connection": "close",
  "x-amz-id-2": "xYo+0Cqwshbednb/QdJKxaDkeD3xbrALSFmXlMC7cTZusti7Zq/twsAKWnvDPO4mrDv/Nt/o3DoOPwSIQj6PHjUuT/nnvjQS",
  "x-amz-request-id": "32DD47D1006BF785",
  "content-type": "application/xml",
  "content-length": "0"
}
```

**Comment by acarstoiu** [comment]
I get the same thing on one of my machines and it seems an environment problem, but I have no clue.

**Comment by benbracha** [comment]
I think it was because many S3 issues AWS had today.
We used the CDN and it works:
phantomjs_cdnurl=http://cnpmjs.org/downloads

**Comment by nicks** [comment]
ya, i'm guessing there was some sort of temporary outage.

the README has instructions on how to install from another cdn or from a pre-downloaded binary (https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs)
