### ISSUE TITLE
Phantomjs v1.9.18 no longer build with node 0.8.x

### ISSUE THREAD

**Issue by lxe** [Medium/phantomjs#370]
Looks like upgrading fs-extra here:

https://github.com/Medium/phantomjs/commit/87e105a33dfdab97f503c82100ea958eedf640ff

Caused the builds on node 0.8x to fail due to a `setImmediate` call.

I think dropping support was planned, but I'd like to track this anyways.

**Comment by nicks** [comment]
My understanding is that node 0.8 got end-of-lifed, and does not even get security fixes. see: https://github.com/nodejs/LTS/issues/30

If you are still using node 0.8, you should move off of it ASAP.

Is there some other action you'd like us to take here?

**Comment by nicks** [comment]
I'm closing this as "won't fix"
