### ISSUE TITLE
npm install -g uncss failed

### ISSUE THREAD

**Issue by ilvy** [Medium/phantomjs#372]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "uncss"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jiangxuefeng1\npm-debug.log

**Comment by nicks** [comment]
there's not really enough information in this snippet for anyone to help you. You'll need to provide more of the log.

have you tried looking at the troubleshooting faq?
https://github.com/Medium/phantomjs#troubleshooting
