### ISSUE TITLE
Error making request

### ISSUE THREAD

**Issue by zhuochenKIDD** [Medium/phantomjs#375]
> ember-precompiler-brunch@1.4.1 postinstall /root/apache-ambari-2.1.0-src/ambari-web/node_modules/ember-precompiler-brunch
> node setup.js postinstall

npm http 304 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits

Error making request.
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by nicks** [comment]
see this item in the FAQ:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
