### ISSUE TITLE
Security issue with npm installer

### ISSUE THREAD

**Issue by jamie-pate** [Medium/phantomjs#382]
I know most people don't have multi-user systems with untrusted users, that also run production node/phantomjs but if you do, then this:
```
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/[user]/5-4/100d/migadmin/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1441919026028/phantomjs-1.9.8-linux-x86_64 -> /home/[user]/5-4/100d/migadmin/node_modules/phantomjs/lib/phantom
```
is a huge security hole. (imagine if you did `sudo npm install phantomjs -g` and there was a rogue copy at that location)

A nice fix would be:
A) copy the file to a non-global temp location (with restricted write permissions for other users)
B) confirm the file contents with a checksum/signing

In theory this could also cause permission errors if multiple users tried installing phantomjs via npm on the same machine with a shared tmp dir.

Previously raised upstream at: https://github.com/ariya/phantomjs/issues/13580

**Comment by nicks** [comment]
hmmm...I'm pretty sure that env.TMPDIR is supposed to, by definition, point to a place where it's safe to read and write scratch files. 

If an untrusted user has permissions to write to env.TMPDIR, then that I think that would be a failure of the system administrator? i.e., you're already p0wned, and other unix tools will also be compromised in the same way.

I think this is covered in the POSIX spec, we can look it up if this seems controversial.

**Comment by nicks** [comment]
(i'd personally be fine accepting a patch to add checksum comparisons. but i think you're mistaken about the TMPDIR security model, and believe it would be less secure to roll our own tmpdir security)

**Comment by jamie-pate** [comment]
The issue i'm seeing is that there's no check to make sure the existing archive belongs to the current user. Any user could place a file at that location with that name, with any contents, and it'll be run by the user that installs phantomjs. The default permissions for /tmp are drwxrwxrwt. Writing then reading is (probably?) safe, (the file will be created with the uid of the writing user) but reading a file that just happens to exist in that path, not so much.

**Comment by evilaliv3** [comment]
i found this today while working on [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks)  and i've exactly the same concern.
Every user is able to currently put in there a crafted malicous package and make the malicious code be runned by the user running npm.

**Comment by jamie-pate** [comment]
The mktemp module could help `dir = mktemp.createDirSync('XXX-XXX');`  of
course then you are not persisting across installs any more. You would have
to cache the dir in the users .config somewhere to do that. And check the
ownership before extracting.

**Comment by jamie-pate** [comment]
Hah, nvm I guess? Though baking in a checksum seems like a maintenance nightmare. I guess ppl will be shifting to phantom2 packages anyways?

**Comment by nicks** [comment]
re: "baking in a checksum seems like a maintenance nightmare" - not so much, compared to the other nightmares of managing phantomjs installations (which your last question is a great example of, see https://github.com/Medium/phantomjs#the-latest-version-of-this-package-installs-phantomjs-198-when-is-phantomjs-20-coming)

**Comment by jamie-pate** [comment]
Probably fine as long as the baked in md5 matches the binary indefinitely (for each version of this npm module released.)  I'm aware of the pjs2 crapstorm :)

I have temporarily switched to a karma runner that uses the system version of pjs since 2.0 is just such a step up from 1, but some devs still haven't gotten it to compile. It's acceptable so long as the CI server still runs it for me, but the installer is a much better deal.
