### ISSUE TITLE
PhantomJS-Google-Charts

### ISSUE THREAD

**Issue by doubletaketech** [Medium/phantomjs#389]
I want to be able to generate google charts in Node using PhantomJS

How would I use your npm package with this PhantomJS project
https://github.com/pstephan1187/PhantomJS-Google-Charts

Just not sure where this code would go in the context of node
would I drop this phantomJS code inside here 

    childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
    // handle results 
    })

Just trying to learn how the architecture works between node and phantom so I can pass a chart to my hapi.js/handlebars Views on the server.

I'd appreciate any assistance.
Thanks,
Donnie

**Comment by doubletaketech** [comment]
Does anyone have a sample phantom-script.js file I can use to test to make sure this package is working?

Also, I'm really trying to figure out how I call the PhantomJS-Google-Charts script in the child args. I don't know what file type it needs saved as to be called since childargs requires an external file.

Thanks

**Comment by nicks** [comment]
this repo is an installer, not the main phantomjs project. here's a link to the mailing list:
https://groups.google.com/forum/#!forum/phantomjs

**Comment by doubletaketech** [comment]
I get this error when I run this code 

info Server running at: socket:\\.\pipe\ec591f2f-0852-48e0-bd9c-1a79191fd4f8
{ [Error: Command failed: C:\Program Files\iisnode\www\node_modules\phantomjs\lib\phantom\phantomjs.exe C:\Program Files\iisnode\www\GC.js
Can't open 'C:\Program Files\iisnode\www\GC.js'

]
  killed: false,
  code: 4294967295,
  signal: null,
  cmd: 'C:\\Program Files\\iisnode\\www\\node_modules\\phantomjs\\lib\\phantom\\phantomjs.exe C:\\Program Files\\iisnode\\www\\GC.js' }
Can't open 'C:\Program Files\iisnode\www\GC.js'

when I call this code in my node app
server.route({
	method: 'GET',
	path: '/chart',
	handler: function (request, reply) {
		
		var path = require('path')
		var childProcess = require('child_process')
		var phantomjs = require('phantomjs')
		var binPath = phantomjs.path
		 
		var childArgs = [
		  path.join(__dirname, 'GC.js')
		]
 
		childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
		  // handle results 
		  if(err){
			  console.log(err)
			  
		  }
		  else {
			  console.log(stdout)
		  }
		 
		  reply('chart')
		  //reply.view();
		})
    		
		
		
	}
});

**Comment by doubletaketech** [comment]
ok @nicks . sorry.  just trying to understand how to open phantomJS in node and call a script.
