### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by andyrichard** [Medium/phantomjs#391]
The project I am working on is using phantomjs but recently our builds started failing.
From what I can tell, this was caused by a new version of weak being used in the dnode module that phantom uses.
I tried to create a new project to test the phantomjs install to make sure that was the cause and sure enough it also failed when phantomjs is the only node module to install.

Any ideas on how to get around this?

$ npm install
npm WARN package.json absence.io@0.9.46 No repository field.
npm WARN package.json absence.io@0.9.46 No README data
/

> weak@1.0.0 install c:\Users\Studi\Documents\nodetest\node_modules\phantom\node_modules\dnode\node_modules\weak
> node-gyp rebuild

c:\Users\Studi\Documents\nodetest\node_modules\phantom\node_modules\dnode\node_modules\weak>node "c:\Program Files\n
odejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: x64/node.lib local checksum 8b539aaaa72b00aa6b92b2dc9ee377159eaed4f01d0b7264a3c8ce06ac37971b n
ot match remote 1c93d92da38a85a36b1e93556d16024d7ca6d342f9bfb9aafe066427a35c4928
gyp ERR! stack     at deref (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:299:20)
gyp ERR! stack     at Request.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\instal
l.js:383:24)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\req
uest.js:1096:12)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:907:16
gyp ERR! stack     at process._tickCallback (node.js:372:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
gyp ERR! cwd c:\Users\Studi\Documents\nodetest\node_modules\phantom\node_modules\dnode\node_modules\weak
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing weak@1.0.0
phantom@0.7.2 node_modules\phantom
├── win-spawn@2.0.0
├── traverse@0.6.6
├── shoe@0.0.15 (sockjs@0.3.7)
└── dnode@1.2.2 (jsonify@0.0.0, dnode-protocol@0.2.2)

**Comment by nicks** [comment]
I think you're in the wrong repo.  Thus is 'phantomjs' not 'phantom'

**Comment by andyrichard** [comment]
absolutly correct, sorry thanks for spotting!
