### ISSUE TITLE
Unterminated quoted string syntax error when running inside Docker

### ISSUE THREAD

**Issue by seanemmer** [Medium/phantomjs#392]
Error code is as follows:

```
at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Error: Command failed: /home/agepath/node_modules/mean-seo/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /home/agepath/node_modules/mean-seo/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```

**Comment by siboulet** [comment]
@seanemmer I've been using the phantomjs module inside Docker containers for months without issues. Are you sure this is not an issue with the mean-seo module you're using?

**Comment by seanemmer** [comment]
@siboulet the error suggests the issue originates from the phantomjs binary - I'll try to replicate it in phantom on a standalone basis.  In the meantime - here's the environment, let me know if there's any glaring issues:

Node 0.12
64bit Amazon Linux 2015.03 v2.0.0 running Docker 1.6.2 (AWS Elastic Beanstalk)

**Comment by wilmoore** [comment]
I can confirm that I see the same error within a docker container built from:

```
FROM node:4.2.1
```

**Comment by siboulet** [comment]
@wilmoore haven't had a chance to test under 4.2.1 yet, but am not having any issue under Docker hub image node:0.12-onbuild (Node v0.12.7).

**Comment by wilmoore** [comment]
Thanks for the info @siboulet. I ended up switching to `npm install phantomjs-bin --save-dev` which is working well.

**Comment by lvarayut** [comment]
I'm getting this error while running inside a docker machine using Ubuntu 14.04 with Node v0.12.7.

```sh
09 11 2015 04:01:14.071:INFO [karma]: Karma v0.13.15 server started at http://localhost:8080/
09 11 2015 04:01:14.105:INFO [launcher]: Starting browser PhantomJS
09 11 2015 04:01:14.127:ERROR [phantomjs.launcher]: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs:
09 11 2015 04:01:14.128:ERROR [phantomjs.launcher]: Syntax error: Unterminated quoted string
09 11 2015 04:01:14.129:ERROR [phantomjs.launcher]:

09 11 2015 04:01:14.130:ERROR [launcher]: Cannot start PhantomJS

09 11 2015 04:01:14.134:INFO [launcher]: Trying to start PhantomJS again (1/2).
09 11 2015 04:01:14.149:ERROR [phantomjs.launcher]: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs:
09 11 2015 04:01:14.149:ERROR [phantomjs.launcher]: Syntax error: Unterminated quoted string
09 11 2015 04:01:14.150:ERROR [phantomjs.launcher]:

09 11 2015 04:01:14.152:ERROR [launcher]: Cannot start PhantomJS

09 11 2015 04:01:14.154:INFO [launcher]: Trying to start PhantomJS again (2/2).
09 11 2015 04:01:14.180:ERROR [phantomjs.launcher]: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /www/app/node_modules/phantomjs/lib/phantom/bin/phantomjs:
09 11 2015 04:01:14.181:ERROR [phantomjs.launcher]: Syntax error: Unterminated quoted string
09 11 2015 04:01:14.181:ERROR [phantomjs.launcher]:

09 11 2015 04:01:14.183:ERROR [launcher]: Cannot start PhantomJS

09 11 2015 04:01:14.185:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
```

**Comment by nicks** [comment]
this typically happens when you installed the binary on one platform and tried to run the installed code on another platform, which will not work. dupe #384

**Comment by alber999** [comment]
One common problem when host and guest run different platforms are the phantom binaries, specific for each platform. 

Just add lines below to your Dockerfile to install phantomjs in docker image globally. Forget about any more problems!

```
ENV PHANTOMJS_BIN "/usr/local/bin/phantomjs"
RUN npm i -g phantomjs-prebuilt 
```

If you want more info:
http://www.savethecode.com/docker-runner-for-angular2/

**Comment by ccorcos** [comment]
Just some context for others:

My issue was that I had installed my npm packages, and then mounted the files in docker (including the installed prebuilt phantomjs package). 

The solution was `git clean -fXd` and then `npm install` inside the docker container. Then everything worked.

Thanks for the help 👍

**Comment by QuotableWater7** [comment]
@ccorcos thank you for posting that solution, just worked perfectly 👍

**Comment by enjikaka** [comment]
For me, working with Docker, I solved this by adding `- /path/to/app/node_modules` under volumes in my docker-compose.yml.

Dockerfile:
```
FROM node:latest
RUN mkdir -p /opt/app
WORKDIR /opt/app
ADD package.json /opt/app
RUN npm install
```

docker-compose.yml
```
version: '3'

services:
  app:
    build: .
    volumes:
      - .:/opt/app
      - /opt/app/node_modules

```

Then I just do `docker-compose run app npm run test` to run the tests.

**Comment by rosnk** [comment]
I had to do one more thing then @ccorcos mentioned, 
i had to remove node module inside the docker container as well, before running `npm install` again. npm install with the node module intact did not work in the beginning.
