### ISSUE TITLE
Array.prototype.push.apply() error with karma

### ISSUE THREAD

**Issue by gokussx4** [Medium/phantomjs#394]
Using Chrome or IE as the browser type there is no problem. When running the same unit test through phantomJS this error occurs:
```
TypeError: '[object Object]' is not a valid argument for 'Function.prototype.apply' (evaluating 'response.data')
```

Example code:
```
var data = [];
var otherData = ['1','2','3'];
Array.prototype.push.apply(data, otherData);
```

**Comment by nicks** [comment]
this is the repo for the phantomjs installer. you're looking for https://github.com/Medium/phantomjs

**Comment by gokussx4** [comment]
@nicks 
https://github.com/Medium/phantomjs/issues/394 is where the issue is posted? Sorry I am confused as to how this issue is in the phantomjs installer repo?

**Comment by nicks** [comment]
https://github.com/ariya/phantomjs

**Comment by gokussx4** [comment]
Ok thanks, at first it wasn't ariya so that is why I was confused :)
