### ISSUE TITLE
phantomjs2 fails to install, can't execute install.js

### ISSUE THREAD

**Issue by bubbleshadow** [Medium/phantomjs#395]
After executing npm install --verbose -g I get the following error:

-----------------------------------------------
Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /tmp/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly
npm verb lifecycle phantomjs2@2.0.0~install: unsafe-perm in lifecycle true
npm verb lifecycle phantomjs2@2.0.0~install: PATH: /home/daniel/usrlocal/lib/node_modules/npm/bin/node-gyp-bin:/home/daniel/usrlocal/lib/node_modules/phantomjs2/node_modules/.bin:/home/daniel/usrlocal/lib/node_modules/.bin:/home/daniel/.local/bin:/home/daniel/usrlocal/bin:/home/daniel/.gem/ruby/2.1.0/bin:/home/daniel/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/daniel/bin:/home/daniel/.rvm/bin
npm verb lifecycle phantomjs2@2.0.0~install: CWD: /home/daniel/usrlocal/lib/node_modules/phantomjs2
npm info lifecycle phantomjs2@2.0.0~install: Failed to exec install script
npm verb unlock done using /home/daniel/.npm/_locks/staging-333b40ed528c6ebe.lock for /home/daniel/usrlocal/lib/node_modules/.staging
npm verb stack Error: phantomjs2@2.0.0 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/daniel/usrlocal/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/home/daniel/usrlocal/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid phantomjs2@2.0.0
npm verb cwd /home/daniel
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "node" "/home/daniel/usrlocal/bin/npm" "install" "-g" "--verbose" "phantomjs2"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.
-----------------------------------------------

And here's the log from /home/daniel/npm-debug.log

5524 info lifecycle phantomjs2@2.0.0~install: phantomjs2@2.0.0
5525 verbose lifecycle phantomjs2@2.0.0~install: unsafe-perm in lifecycle true
5526 verbose lifecycle phantomjs2@2.0.0~install: PATH: /home/daniel/usrlocal/lib/node_modules/npm/bin/node-gyp-bin:/home/daniel/usrlocal/lib/node_modules/phantomjs2/node_modules/.bin:/home/daniel/usrlocal/lib/node_modules/.bin:/home/daniel/.local/bin:/home/daniel/usrlocal/bin:/home/daniel/.gem/ruby/2.1.0/bin:/home/daniel/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/daniel/bin:/home/daniel/.rvm/bin
5527 verbose lifecycle phantomjs2@2.0.0~install: CWD: /home/daniel/usrlocal/lib/node_modules/phantomjs2
5528 silly lifecycle phantomjs2@2.0.0~install: Args: [ '-c', 'node install.js' ]
5529 silly lifecycle phantomjs2@2.0.0~install: Returned: code: 1  signal: null
5530 info lifecycle phantomjs2@2.0.0~install: Failed to exec install script
5531 verbose unlock done using /home/daniel/.npm/_locks/staging-333b40ed528c6ebe.lock for /home/daniel/usrlocal/lib/node_modules/.staging
5532 silly rollbackFailedOptional Starting
5533 silly rollbackFailedOptional Finishing
5534 silly runTopLevelLifecycles Starting
5535 silly runTopLevelLifecycles Finishing
5536 silly install printInstalled
5537 verbose stack Error: phantomjs2@2.0.0 install: `node install.js`
5537 verbose stack Exit status 1
5537 verbose stack     at EventEmitter.<anonymous> (/home/daniel/usrlocal/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
5537 verbose stack     at EventEmitter.emit (events.js:110:17)
5537 verbose stack     at ChildProcess.<anonymous> (/home/daniel/usrlocal/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5537 verbose stack     at ChildProcess.emit (events.js:110:17)
5537 verbose stack     at maybeClose (child_process.js:1015:16)
5537 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
5538 verbose pkgid phantomjs2@2.0.0
5539 verbose cwd /home/daniel
5540 error Linux 3.19.0-28-generic
5541 error argv "node" "/home/daniel/usrlocal/bin/npm" "install" "-g" "--verbose" "phantomjs2"
5542 error node v0.12.7
5543 error npm  v3.3.5
5544 error code ELIFECYCLE                                                                        
5545 error phantomjs2@2.0.0 install: `node install.js`
5545 error Exit status 1
5546 error Failed at the phantomjs2@2.0.0 install script 'node install.js'.

----------------------------------------------------

Any help would be appreciated, thank you.

**Comment by bubbleshadow** [comment]
I forgot to add that phantomjs 1.9.8 installs successfully.

**Comment by nicks** [comment]
Thanks for filing! But the phantomjs2 project is in another repo.
https://www.npmjs.com/package/phantomjs2
https://github.com/zeevl/phantomjs2
