### ISSUE TITLE
feature request: webdriver.load.strategy=unstable

### ISSUE THREAD

**Issue by duffj** [Medium/phantomjs#400]
Hi, I use PhantomJS in conjunction with Selenium (Java/Scala bindings) to test my websites. I'm currently working with a target site where one of the pages is unstable and sometimes never finishes loading, due to the high number of analytics trackers and various other bits of AJAX on the page. This is making our acceptance tests unstable. I would like to be able to tell Selenium not to bother waiting for the entire page to load. Is this possible to do in PhantomJS? It seems to be possible in Firefox using `webdriver.load.strategy=unstable`, it would be great to have something similar in PhantomJS, either by disabling AJAX requests or something similar. Thoughts?

**Comment by mclarke47** [comment]
+1

**Comment by nicks** [comment]
this repo is just the phantomjs installer. you're looking for https://github.com/ariya/phantomjs
