### ISSUE TITLE
PhantomJS install fails via npm

### ISSUE THREAD

**Issue by deltreey** [Medium/phantomjs#407]
This is the same issue from #161 

The issue is not resolved.  The workaround (downloading the file manually from bitbucket and saving it to the temp folder where npm reads it from) makes it work, but is not a long-term resolution.

I encountered this yesterday with node v5.0.0 on Windows 10.  The only way I was able to fix it was to export the verbose logs to a file so I could find the temp folder where npm was saving the download.  The error message was simply "Install failed unexpectedly".  I can provide full logs, but they'll be as beneficial as they are on the other 5 issues about this problem (not at all).

Alternatively, I am available for testing and further details.  I suspect this is related to the fact that npm is searching for phoenix v1.9.18 and bitbucket is returning v1.9.8 but that is just speculation.  Another potential option is that 90% of bitbucket's servers are returning one http response, and 10% are returning another.

This error is certainly transient, and I suspect that is due to the download failing.  Since it uses a temp folder, my suspicion is that there is no check to ensure the download was successful, or the check returns "Install failed unexpectedly" which is followed by successful install if the file exists from a previous download attempt.

**Comment by gihrig** [comment]
+1 on the confusion!

AFAICT, The current version is actually 1.9.8 or 2.0. 1.9.8 is available from npm, 2.0 is not. npm is erroneously reporting 1.9.18 as current.

It would be great if npm could be updated and at least direct people to phantomjs.org for the current version.

Details:

It seems the error is npm's assertion that the current version is 1.9.18.
[https://www.npmjs.com/package/phantomjs](https://www.npmjs.com/package/phantomjs)

Bitbucket master is empty
[https://bitbucket.org/ariya/phantomjs/branch/master](https://bitbucket.org/ariya/phantomjs/branch/master)

The latest Bitbucket branch, 1.9 contains version 1.9.8, with earlier references to 1.9.7
[https://bitbucket.org/ariya/phantomjs/branch/1.9](https://bitbucket.org/ariya/phantomjs/branch/1.9)

From the above I conclude that 1.9.8 is the latest 1.9 branch.

However, [http://phantomjs.org/](http://phantomjs.org/) provides 2.0 as the latest stable version, which is maintained here on Github, and not available as an npm install.

**Comment by deltreey** [comment]
That's not npm's fault. https://github.com/Medium/phantomjs/blob/master/package.json
The package.json file shows version number as 1.9.18

**Comment by deltreey** [comment]
ran into this on my mac today.  I can confirm that it doesn't work without the workaround on OSX El Capitan

Found this SO post while I was at it.
http://stackoverflow.com/questions/23823319/yeoman-generator-always-get-some-error
