### ISSUE TITLE
Unable to run phantomJS on karma

### ISSUE THREAD

**Issue by ferryarman** [Medium/phantomjs#408]
Hi, I'm encountered a problem recently with PhantomJS library.

$ karma start

Log result:
---
Karma v0.13.15 server started at http://localhost:9876/
Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket H1vRWOIqgBCUjb_bAAAA with id 36694801
***PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.
  at /Users/farman/.../tests.webpack.js:122637 <- webpack:///~/crypto-browserify/rng.js:14:0***

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (2.21 secs / 0 secs)

====
Module versions:
- OSX: El Capitan 10.11.1
- node: 5.0.0
- Karma: 0.13.15
- karma-phantomjs-launcher: 0.2.1
- phantomjs: 1.9.18

I've checked the forum, but still not solving the issue:
https://github.com/AngularClass/angular2-webpack-starter/issues/45

But, interestingly when I switched the launcher to karma-firefox-launcher, it works fine.
So, I suspect there's an internal issue on phantomJS version 1.9.18.

Any advice ?

**Comment by nicks** [comment]
This means your code fails on phantomjs, which is likely not phantomjs's fault.

Also, it's worth pointing out that this repo is just an installer for phantomjs, we do not maintain the main phantomjs tool. For problems with phantomjs, see http://phantomjs.org/
