### ISSUE TITLE
Unable to install PhantomJS on first run

### ISSUE THREAD

**Issue by gonzochic** [Medium/phantomjs#410]
When I call <code>npm install</code> in my project and no node_modules are downloaded the installation will fail with following error:

```bash
> phantomjs@1.9.18 install /opt/build/jenkins/workspace/HEAD/react/node_modules/phantomjs
> node install.js

module.js:338
   throw err;
         ^
Error: Cannot find module './util'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (/opt/build/jenkins/workspace/HEAD/react/node_modules/adm-zip/zipEntry.js:1:75)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
npm ERR! Linux 2.6.32-431.5.1.el6.x86_64
npm ERR! argv "/opt/build/tools/node-v0.12.6-linux-x64/bin/node" "/opt/build/tools/node-v0.12.6-linux-x64/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
```

When I run the <code>npm install</code> again it works. The problem is, it should work on the first time. I got this problem when I updated my private npm proxy repository. 

I checked what Version could have run before and I found a selection of:
* phantomjs@1.9.17
* phantomjs@1.9.18
* adm-zip@0.2.1
* adm-zip@0.4.4

Do you have any clue what it could be? I saw that there were some refactoring in the install.js file. 
THX

**Comment by nicks** [comment]
this seems like an internal npm problem, and it's misattributing the error? Notice that the stack trace says it's inside adm-zip/zipEntry.js and failing to load adm-zip/util

a shot in the dark is that npm is trying to merge the version of adm-zip in react with the one in phantomjs and is screwing it up

**Comment by gonzochic** [comment]
Ok, i tried to rollback to 1.9.17 and it seems to work there. But I can't find any reason for that in the history of <code>install.js</code>.

**Comment by nicks** [comment]
as i pointed out, this is a bug in how npm is installing adm-zip, and unrelated to phantomjs
