### ISSUE TITLE
`npm install spm` on ubuntu

### ISSUE THREAD

**Issue by blusewang** [Medium/phantomjs#412]
If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "spm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bluse/npm-debug.log

**Comment by nicks** [comment]
I suspect you have to install node on PATH. See:
https://github.com/Medium/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node

If that is not the case, please reopen with the full logs.

**Comment by blusewang** [comment]
This problem I have resolved!
It's becuse China GFW FireWall! It made me some package download timeout!
I used shadowsocks geted them! and installed successfull!
Thank you!

**Comment by nicks** [comment]
Yay!
