### ISSUE TITLE
Install of v1.9.19 is not working on ARM architecture

### ISSUE THREAD

**Issue by shouze** [Medium/phantomjs#418]
```
npm ERR! Linux 4.2.5-263
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
````

I could give you some details from /app/npm-debug.log but as I'm building it with docker... it would imply that I keep my generated image.

**Comment by nicks** [comment]
correct, there are no ARM binaries. if you build your own and put it on PATH, the installer will pick it up.

**Comment by nicks** [comment]
fwiw, the installer is also complaining that you don't have `node` installed. Instead, you have `/usr/bin/nodejs` installed, which is not the same. See:
https://github.com/Medium/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node

**Comment by shouze** [comment]
@nicks yes for `nodejs` you're right. So i haven't this message with previous release of phantom, so does it mean that ARM binaries are available or install process was less strict?

**Comment by nicks** [comment]
Uhhhh...i think you are confused.

This package has always required that `node` is on PATH.

There have never been officially blessed ARM binaries, see
https://bitbucket.org/ariya/phantomjs/downloads
