### ISSUE TITLE
Issue installing phantomjs

### ISSUE THREAD

**Issue by llogr** [Medium/phantomjs#420]
I'm having an issue install phantomjs 1.9.19 on my Windows 7 machine. When I run npm install it downloads all of the dependencies for phantomjs but then fails when it runs the install.js script.

I've also tried checking out the repository and running npm install in the checked out directory and see the same issue. The interesting thing here is that when I run ```node install.js```  after the npm install failure the install.js script works as expected and configures the phantomjs executable.

I've tried all sorts of things including:
* many different versions of node/npm spanning 0.10.0 - 5.1.1
* 32/64 bit installations
* removing all trace of node/nvm from my machine and reinstalling
* different networks to check for corporate firewall issues

Can anyone suggest anything else to try? I'm at a loss as to what to try next.

System Info
node v4.2.3
npm v3.5.0

Output from running npm install phantomjs in an empty directory below and npm-debug.log attached

```
C:\Gary\Sandbox\tp>npm install phantomjs

> phantomjs@1.9.19 install C:\Gary\Sandbox\tp\node_modules\phantomjs
> node install.js

Install exited unexpectedly
npm WARN tp@1.0.0 No description
npm WARN tp@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Gary\\Application\\nodejs\\node.exe" "C:\\Users\\llogr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Gary\Sandbox\tp\npm-debug.log
```
[npm-debug.txt](https://github.com/Medium/phantomjs/files/52140/npm-debug.txt)

**Comment by nicks** [comment]
you need to install `node` on PATH, see
https://github.com/Medium/phantomjs#installation-fails-with-spawn-enoent

**Comment by llogr** [comment]
Thanks. I don't think that is it though since straight after the failure I can run ```node -v``` and get the version output. See the chunk of console output below.

Notice that the error isn't ENOENT but ELIFECYCLE as the install.js script starts to run and then fails giving the "Install exited unexpectedly" message from the install.js file in the phantom repo. I've started trying to trace it through but the error comes after the kew call on line 306 in the tryPhantomjsInLib function. I just don't know why....

==========
llogr /c/Gary/Sandbox/tp
$ echo $PATH
/k/bin:.:/usr/local/bin:/mingw/bin:/bin:/c/ProgramData/Oracle/Java/javapath:/c/Gary/Applications/Sublime Text 3:/c/Gary/Applications/Java/jdk1.8.0_05/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/Gary/Applications/Gow/bin:/c/Gary/Applications/SlikSvn/bin:/c/Program Files/TortoiseSVN/bin:/c/Gary/Applications/Vagrant/bin:/c/Python27:/c/Gary/Applications/gradle-2.2.1/bin:/c/Program Files/TortoiseGit/bin:/c/Program Files (x86)/git/cmd:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/c/Program Files/Microsoft SQL Server/110/Tools/Binn/:/bin:/c/Program Files/MongoDB 2.6 Standard/bin:/c/Windows/Microsoft.NET/Framework/v4.0.30319:/c/Program Files (x86)/Google/Chrome/Application:/c/Python27/Scripts:/c/Gary/Applications/RabbitMQ Server/rabbitmq_server-3.5.3/sbin:/c/Gary/Applications/Amazon/AWSCLI/:/c/Gary/Applications/Tools:/c/Gary/Applications/Brackets/command:%USERPROFILE%/.dnx/bin:/c/Program Files/Microsoft DNX/Dnvm/:%NVM_HOME%:%NVM_SYMLINK%:/c/Gary/Applications/atlassian-plugin-sdk/bin:/c/Gary/Applications/Boot2Docker for Windows:/c/Users/llogr/.babun:/c/Users/llogr/AppData/Local/atom/bin:/c/Users/llogr/AppData/Local/atom/bin:/c/Gary/Applications/Docker Toolbox:/c/Users/llogr/AppData/Roaming/npm:/c/Gary/Applications/nvm:/c/Gary/Applications/nodejs
llogr /c/Gary/Sandbox/tp
$ which node
/c/Gary/Applications/nodejs/node
llogr /c/Gary/Sandbox/tp
$ npm install phantomjs

> phantomjs@1.9.19 install c:\Gary\Sandbox\tp\node_modules\phantomjs
> node install.js

Install exited unexpectedly
npm WARN tp@1.0.0 No description
npm WARN tp@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Gary\\Applications\\nodejs\\node.exe" "c:\\Users\\llogr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Gary\Sandbox\tp\npm-debug.log
llogr /c/Gary/Sandbox/tp
$ node -v
v4.2.3
llogr /c/Gary/Sandbox/tp
$
