### ISSUE TITLE
It asked me to report this error

### ISSUE THREAD

**Issue by tallchap67** [Medium/phantomjs#424]
C:\Projects\foundation-zurb-template-master>npm install
npm WARN optional dep failed, continuing fsevents@1.0.6

phantomjs@1.9.19 install C:\Projects\foundation-zurb-template-master\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_modules\phantomjs

node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\JONHUR~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.

Error: getaddrinfo ENOTFOUND bitbucket.org bitbucket.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

Please report this full log at https://github.com/Medium/phantomjs

**Comment by nicks** [comment]
this means that your internet connection was not able to download the file, see 
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
for troubleshooting steps
