### ISSUE TITLE
Using private registry with self signed certificate

### ISSUE THREAD

**Issue by Mic75** [Medium/phantomjs#428]
Hello,

I am  using my own npm registry with a self signed certificate.
I have set up the [cafile](https://docs.npmjs.com/misc/config) npm config value to use a file containing the certificate.

However I get the following error from phantomsjs installation:

    Error making request.
    Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:936:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:467:8)

Is there any other solution than turning off [strict-ssl](https://github.com/Medium/phantomjs#i-am-behind-a-corporate-proxy-that-uses-self-signed-ssl-certificates-to-intercept-encrypted-traffic) ?

**Comment by nicks** [comment]
you can also use npm's ca config
https://docs.npmjs.com/misc/config#ca
