### ISSUE TITLE
Failed at the phantomjs@1.9.19 install script 'node install.js'.

### ISSUE THREAD

**Issue by PaulGuo** [Medium/phantomjs#430]
```
➜  npm install -g phantomjs   
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@1.9.19 install /usr/local/lib/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/gm/mzhxxt5x32q10xzkrj9wjyzc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...



  [=---------------------------------------] 3% 0.0s
Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "phantomjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
```

**Comment by katrotz** [comment]
Almost same scenario, although I can download the archived phantomJS from the specified link via browser:

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/n1/j345jpn17gnbs2gsnj8whrgr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "984D70491D508D56",
  "x-amz-id-2": "ZpMhUpGyOWfOxcIzXOyPRJms7F5V7+dcwhEPD26YIFZFtL9qReuNtkG2ok+eoyYVRBDhokW2xUw=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Tue, 29 Dec 2015 08:40:26 GMT",
  "server": "AmazonS3",
  "connection": "close"
}

````

**Comment by jrobison153** [comment]
I'm having the same issue from my Jenkins build job

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "4B3D561BE913AEEB",
  "x-amz-id-2": "IyvlsJALvRK3RZKpNjvDfjH3JQtqW4qZQsKEjEGq2q7pAPO7/BQSOHdSR/5tAgH/tT1bvCtX07Q=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Tue, 29 Dec 2015 16:34:24 GMT",
  "server": "AmazonS3",
  "connection": "close"
}

However when I run the same install from my Windows dev box I have no issues. I'll try @katrotz npm config suggestion to see if that helps.

Note that the exact same Jenkins build jobs worked on December 22nd and started failing on the builds today, December 22nd.

**Comment by jrobison153** [comment]
okay, thanks to @katrotz for the work around. Anyone have any idea what the root cause of this problem is?

**Comment by MrDefinite** [comment]
I met same issue on windows 2008, when I tried to install karma-phantomjs-launcher...

**Comment by nicks** [comment]
The OP's error message is that the internet connection was blocked. see https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout for troubleshooting

**Comment by qorbani** [comment]
I had exact same issue and nothing works except following command:

```bash
npm config set unsafe-perm true
```

**Comment by jorgeramirez** [comment]
thanks! @qorbani that solved the issue for me too.

**Comment by simonbogarde** [comment]
@qorbani Awesome! Thanks a bunch!

**Comment by gpincheiraa** [comment]
@qorbani  thanks! works for me!

**Comment by iller7** [comment]
@qorbani cheers, working here thanks to you!

**Comment by digimix** [comment]
Works for me, resolved issue on Magento 2 (dev branch) npm install.
