### ISSUE TITLE
getting error install phantomjs2

### ISSUE THREAD

**Issue by ronikb** [Medium/phantomjs#431]
I am trying to install HospitalRun frontend in one of my Ubuntu 14.04 droplet. This installation needs  phantomjs2. During the installation I cannot install phantomjs2 with the following error log. It will be good to get a resolution for this

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'phantomjs2' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 silly fetchPackageMetaData phantomjs2
5 silly fetchNamedPackageData phantomjs2
6 silly mapToRegistry name phantomjs2
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry uri https://registry.npmjs.org/phantomjs2
10 verbose request uri https://registry.npmjs.org/phantomjs2
11 verbose request no auth needed
12 info attempt registry request try #1 at 5:43:34 AM
13 verbose request id 5fe918b21320a809
14 verbose etag "6B2XAR6GBD5LDI0RFTYNF8KUC"
15 http request GET https://registry.npmjs.org/phantomjs2
16 http 304 https://registry.npmjs.org/phantomjs2
17 verbose headers { date: 'Wed, 06 Jan 2016 10:43:34 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   'cache-control': 'max-age=300',
17 verbose headers   etag: '"6B2XAR6GBD5LDI0RFTYNF8KUC"',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-iad2124-IAD',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1452077014.368535,VS0,VE18',
17 verbose headers   vary: 'Accept' }
18 silly get cb [ 304,
18 silly get   { date: 'Wed, 06 Jan 2016 10:43:34 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     'cache-control': 'max-age=300',
18 silly get     etag: '"6B2XAR6GBD5LDI0RFTYNF8KUC"',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-iad2124-IAD',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1452077014.368535,VS0,VE18',
18 silly get     vary: 'Accept' } ]
19 verbose etag https://registry.npmjs.org/phantomjs2 from cache
20 verbose get saving phantomjs2 to /home/roni_baby/.npm/registry.npmjs.org/phantomjs2/.cache.json
21 silly bugs url https://github.com/zeevl/phantomjs2/issues
22 verbose stack Error: spawn xdg-open ENOENT
22 verbose stack     at exports._errnoException (util.js:855:11)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
22 verbose stack     at onErrorNT (internal/child_process.js:344:16)
22 verbose stack     at nextTickCallbackWith2Args (node.js:455:9)
22 verbose stack     at process._tickCallback (node.js:369:17)
23 verbose cwd /opt/hospitalrun-frontend
24 error Linux 3.13.0-71-generic
25 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "phantomjs2"
26 error node v5.3.0
27 error npm  v3.5.2
28 error path xdg-open
29 error code ENOENT
30 error errno ENOENT
31 error syscall spawn xdg-open
32 error enoent spawn xdg-open ENOENT
33 error enoent spawn xdg-open ENOENT
33 error enoent This is most likely not a problem with npm itself
33 error enoent and is related to npm not being able to find a file.
34 verbose exit [ 1, true ]

**Comment by nicks** [comment]
You're in the wrong project. We're not associated with phantomjs2
