### ISSUE TITLE
plans to refactor to use rc (instead of npmconf)?

### ISSUE THREAD

**Issue by jgravois** [Medium/phantomjs#432]
installing using npm `2.14.12` results in this word of warning:
```
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
```
it appears that `npmconf` has been deprecated in favor of [`rc`](https://github.com/dominictarr/rc).  do y'all have any plans to refactor this wrapper to support the suggested lib?

**Comment by nicks** [comment]
No, `rc` would be the incorrect approach. The whole point is that this is an installer script, so should use the same configuration that NPM is using. 

When I asked the NPM folks about this, they agreed, though the sticking point was what the API should be for packages that know what they're doing and need the NPM configuration, without misleading people that are looking for app-specific configuration (which is what `rc` provides).

**Comment by jgravois** [comment]
thanks for taking the time to clarify!

**Comment by tripu** [comment]
> The whole point is that this is an installer script, so should use the same configuration that NPM is using.

@nicks, why not [use `npm` programmatically](https://github.com/npm/npm#using-npm-programmatically) instead of `npmconf`, then?

Using the `npm` API isn't recommended, but less so is using a deprecated package like `npmconf`&hellip;
