### ISSUE TITLE
No binary available for linux/arm architecture

### ISSUE THREAD

**Issue by henrywright** [Medium/phantomjs#433]
Hey guys,

When I run `sudo npm install`, I get the error:

```
PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
```

My system architecture is `armhf`.

**Comment by jzaefferer** [comment]
Do any of the 2.1.1 binaries work for you? https://bitbucket.org/ariya/phantomjs/downloads

If not, there's nothing this project can do.

**Comment by henrywright** [comment]
No because those are all `x86-64` etc. I'd need `armhf`. Looks like I'm out of luck :cry:

**Comment by jzaefferer** [comment]
You could file an issue in the upstream project. This should be closed.

**Comment by fnoop** [comment]
```
sudo apt -y install phantomjs
QT_QPA_PLATFORM=offscreen npm install
```
