### ISSUE TITLE
Update to PhantomJS 2.1

### ISSUE THREAD

**Issue by jzaefferer** [Medium/phantomjs#437]
PhantomJS 2.1 was (finally) released today: https://groups.google.com/d/msg/phantomjs/Jp4sDXrfmNg/I5J5TBFBDQAJ

I'm interested in updating [grunt-contrib-qunit](https://github.com/gruntjs/grunt-contrib-qunit) to PhantomJS 2.1, this is the end of the dependency chain.

I'll look into creating a pull request for the update.

**Comment by nicks** [comment]
dupe #288

**Comment by puzrin** [comment]
:+1:
