### ISSUE TITLE
The no_proxy variable gets ignored

### ISSUE THREAD

**Issue by tdietrich513** [Medium/phantomjs#451]
I've created a local mirror of the phantomJS binaries for my internal CI servers to make use of. Because it's local, we would like not to use the proxy server to download the binaries, however it does not seem to respect the no_proxy variable which would tell it not to do so. 

`Request` as of several versions ago properly handles all proxy variables, so the duplication of logic within this package on getting proxy information is unnecessary. 

pull request #450 removes the custom proxy logic and allows the request package to handle it.

**Comment by nicks** [comment]
Per discussion on #450, we're keeping the current behavior to mirror the npmrc settings.

**Comment by tdietrich513** [comment]
Your current behavior does not mirror npm with respect to .npmrc. 

If your .npmrc does not contain proxy settings, npm will use environment variables as a fallback, and will respect the no_proxy variable. 

I currently have no proxy settings in my .npmrc, but this phantomjs package still attempts to use the environment variable for the proxy server without respecting the no_proxy variable. I believe this is because process.env.npm_config_proxy and it's brothers are back filled with the environment proxy settings. The presence of a value in this variable does not always indicate that there is a proxy setting in .npmrc

**Comment by nicks** [comment]
it seems like npm should be fixed so that it doesn't populate the process.env.npm_config_* proxy stuff in that case?

**Comment by nicks** [comment]
more generally, we're trying really hard to respect the settings that NPM is giving us.

If we try to be "smarter" than NPM, we'll descend into versioning hell, with environments overriding each other in complex ways in different versions.

There are probably multiple ways to proceed here. One way would be to the npm_config_no_proxy to NPM, and then use it here. Another would be to have a more explicit API for NPM to communicate to installers what the proxy settings ought to be.
