### ISSUE TITLE
Install the dependencies on Windows

### ISSUE THREAD

**Issue by skilledDeveloper** [Medium/phantomjs#452]
I was able to install the new version on Windows 10 but only after installing Python and adding it to the PATH.
It would be nice if this package could install Python first as it's not installed on any version of Windows.

**Comment by nicks** [comment]
this does not require python, i think you're confused.

**Comment by skilledDeveloper** [comment]
Hmm that's weird. 
For the records, I ran `npm install -g phantomjs`  and in last steps (after downloading the zip file, etc), it clearly complained about not being able to find `python`. That's why I installed it and tried again and it worked!
After seeing your comment I uninstalled `python` and `phantomjs` npm package and reinstalled the packge. This time it didn't complain about python.
