### ISSUE TITLE
Add arm binaries to https://bitbucket.org/ariya/phantomjs

### ISSUE THREAD

**Issue by shouze** [Medium/phantomjs#456]
here's a phantomjs 2.0 available binary available here for armv7 ARCH:
https://github.com/mitghi/phantomjs-2.0.0-armv7

would you add it to https://bitbucket.org/ariya/phantomjs/downloads?
This way, pretty easy to add it to [install.js script](https://github.com/Medium/phantomjs/blob/121f9015c961e0507dbb72d77cc05a2d308f91ea/install.js#L404-L418)

**Comment by mikesherov** [comment]
@shouze thanks for contributing. This is the wrong repo. You're looking for ariya/phantomjs

**Comment by nicks** [comment]
yup, I think your best bet is to ask https://github.com/ariya/phantomjs/issues if they'd be willing to accept an ARM build, or help making one as part of their release.

**Comment by nicks** [comment]
as a workaround, you can also install phantomjs on PATH and this installer will use that one
https://github.com/Medium/phantomjs#using-phantomjs-from-disk
