### ISSUE TITLE
Problems on installation on Ubuntu 12 LTS

### ISSUE THREAD

**Issue by weblogixx** [Medium/phantomjs#459]
Hi,

first thank you for this product, really helps with unit testing and stuff like that.

I just tried to use phantomjs-prebuild 2. It runs great on Windows and Macs, but seems to have problems while installing on a linux machine.

When installing it via npm install phantomjs-prebuild I get the following errors:

```bash
.....
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar: Conflicting compression options
Try `tar --help' or `tar --usage' for more information.
]
.......
```

The problem seems to be that Ubuntu 12 (possibly later versions, too?) to always error out when multiple compression options (like jxf) are given in the installer. I was only able to untar it when I left out the j switch.

Could you please have look at that problem?

**Comment by nicks** [comment]
What version of tar do you have installed? What version of bzip2 do you
have installed?

**Comment by weblogixx** [comment]
Hi @nicks,

we currently have:

tar --version
tar (GNU tar) 1.26

---

and:

bzip2 --version
bzip2, a block-sorting file compressor.  Version 1.0.6, 6-Sept-2010.

**Comment by nicks** [comment]
Is it possible that you have some sort of non-portable wrapper around `tar`?

`jxf` is a standard and portable set of tar options (cf https://www.gnu.org/software/tar/manual/html_node/Short-Option-Summary.html). This is the first time I've ever heard of someone having this problem.

**Comment by weblogixx** [comment]
Hi @nicks,

yes, I too found it strange. I will try to test against a different Ubuntu LTS system and compare the output. Will post the dpkg output of the files and will have a look into the bzip and tar executables as well.

Thank you for the quick reply!

**Comment by iammerrick** [comment]
We're seeing same issue here.

**Comment by iammerrick** [comment]
For us it doesn't look like tar file at all, The folder it downloads is different than the one it tries to untar.

**Comment by nicks** [comment]
@iammerrick : to confirm, you're getting the error message `tar: Conflicting compression options`?

**Comment by iammerrick** [comment]
OH my goodness I'm sorry no, we are getting:

```
11:33:51 Found PhantomJS at /usr/local/bin/phantomjs ...verifying
11:33:51 PhantomJS detected, but wrong version 1.9.2 @ /usr/local/bin/phantomjs.
11:33:51 Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:33:51 Saving to .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:33:51 Receiving...
11:33:54 
11:33:54 Received 22866K total.
11:33:54 Extracting tar contents (via spawned process)
11:33:54 Error extracting archive
11:33:54 Phantom installation failed { [Error: Command failed: tar jxf .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:33:54 tar (child): .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2: Cannot open: No such file or directory
11:33:54 tar (child): Error is not recoverable: exiting now
11:33:54 tar: Child returned status 2
11:33:54 tar: Error is not recoverable: exiting now
11:33:54 ]
11:33:54   killed: false,
11:33:54   code: 2,
11:33:54   signal: null,
11:33:54   cmd: 'tar jxf .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
11:33:54 tar (child): .tmp-npm-install/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2: Cannot open: No such file or directory
```
Is it because our tmp dir is relative?

**Comment by nicks** [comment]
you should probably open a different bug then

**Comment by iammerrick** [comment]
Happy to!

**Comment by weblogixx** [comment]
Just checked it, there are no other libraries or wrappers for tar or bzip. The file gets downloaded correctly, if I use bzip2 and untar it, I get a working binary. Any clues?

**Comment by weblogixx** [comment]
@nicks: It is in fact a problem with the tar binary on the machine. I do not know what caused it. I have removed gnu tar in favor of bsdtar on this machine and now it works correctly. Never had such a problem before.

**Comment by nicks** [comment]
weird. thanks for reporting back!
