### ISSUE TITLE
Update Readme outdated comment -- > From the phantomjs maintainer, seems like not working on CentOS 5 ..

### ISSUE THREAD

**Issue by EFF** [Medium/phantomjs#460]
I haven't tried on CentOS 5 but from what the phantomjs maintainer says, it seems like it's not working. If phantom-prebuilt is really working on CentOS 5 please comment on [this issue](https://github.com/ariya/phantomjs/issues/13940).

If not, please update the Linux note on the readme

**Comment by nicks** [comment]
done! thanks for pointing that out.
