### ISSUE TITLE
build jwplayer  error (The network has over the wall）

### ISSUE THREAD

**Issue by 12345nbaa** [Medium/phantomjs#471]
localhost:jwplayer-master lixiaopeng$ sudo npm install
Password:

npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
-
> phantomjs@1.9.19 install /Users/lixiaopeng/Html5/JWPlayer/jwplayer-master/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /Users/lixiaopeng/Html5/JWPlayer/jwplayer-master/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lixiaopeng/Html5/JWPlayer/jwplayer-master/npm-debug.log
localhost:jwplayer-master lixiaopeng$

**Comment by nicks** [comment]
sorry you're having trouble, please read
https://github.com/Medium/phantomjs#i-tried-again-but-i-get-econnreset-or-etimedout-consistently
for workarounds when your connection is blocked

**Comment by 12345nbaa** [comment]
Thanks, I have already been solved this issue.  Because the network is too poor !
