### ISSUE TITLE
Replace md5 with Sha

### ISSUE THREAD

**Issue by baderbuddy** [Medium/phantomjs#475]
If we replace the dependency on md5 with using sha (1 or 2), it'll increase the security of the download as well as removing the dependency on md5 which is quite old.

**Comment by nicks** [comment]
we would accept a pr for this

**Comment by connesc** [comment]
Done !

This was super easy since I have just replaced the `md5` dependency with [`hasha`](https://github.com/sindresorhus/hasha), which supports multiple hashing algorithms.
