### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by klzns** [Medium/phantomjs#48]
I can't install phantomjs on Windows. I'm using Node v0.10.4.

At some point of the installation, it shows this error:

> phantomjs@1.9.0-2 install C:\Users\Breno\projects\teste\node_modules\phantomjs
> node install.js

CreateProcessW: O sistema nÒo pode encontrar o arquivo especificado.
npm ERR! phantomjs@1.9.0-2 install: `node install.js`
npm ERR! `cmd "/c" "node install.js"` failed with 127
npm ERR!
npm ERR! Failed at the phantomjs@1.9.0-2 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"
 "i" "phantomjs"
npm ERR! cwd C:\Users\Breno\projects\teste
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Breno\projects\teste\npm-debug.log
npm ERR! not ok code 0

Do you have any idea of what am I doing wrong? Or what possibly could be wrong?

Thanks in advance!

**Comment by tspaeth** [comment]
Just as an additional side note, as this is the primary page you'll get to when searching with google on problems.
In a continuous - integration environment with e.g. Jenkins as the build server and a gradle-grunt - nodejs world, where the worker slaves don't have a local node installation, the execution of the preinstall-script "node install.js" will also fail without any specific reason.
After digging deeper into the reasons: It is not the script that fails. It is simply the fact, that the npm install command will not find the node.exe in the PATH automatically if not configured 100% properly. So in that case, the error is halfway a false positive...
Just in case, somebody is coming here and wondering, why the installer fails. This could also be a possibility: No node.exe in PATH set... :-)

**Comment by d33tah** [comment]
Quick note: in my case the error was caused by the lack of `tar` binary installed.

**Comment by smewp** [comment]
I ran into this error today on Windows 10 and thanks to the note from @tspaeth I solved it. I found I had two entries for node in my PATH, including one earlier version I had previously uninstalled.
