### ISSUE TITLE
Problems with NPM

### ISSUE THREAD

**Issue by grandi85** [Medium/phantomjs#487]
C:\Users\agrimm\Documents\GitHub\predix-seed>npm install
npm WARN deprecated npmconf@0.0.24: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm

> phantomjs@1.9.7-15 install C:\Users\agrimm\Documents\GitHub\predix-seed\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-windows.zip
Saving to C:\Users\agrimm\AppData\Local\Temp\phantomjs\phantomjs-1.9.7-windows.zip
Receiving...

Error making request.
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:585:8)

Please report this full log at https://github.com/Medium/phantomjs

> phantomjs@1.9.19 install C:\Users\agrimm\Documents\GitHub\predix-seed\node_modules\karma-phantomjs-launcher\node_modules\phanto
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\agrimm\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:585:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.7-15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.7-15 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\agrimm\Documents\GitHub\predix-seed\npm-debug.log

C:\Users\agrimm\Documents\GitHub\predix-seed>npm install

**Comment by nicks** [comment]
your logs say 'Error: unable to verify the first certificate', which means that someone is blocking your network and passing you a broken/invalid cert. please read the troubleshooting guide:
https://github.com/Medium/phantomjs#troubleshooting

**Comment by grandi85** [comment]
Thanks. I will do so.
