### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by mqliutie** [Medium/phantomjs#491]
PhantomJS not found on PATH
    Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
        Saving to /var/folders/c3/1b05hdrn7hgd2s2gzh7q5n0c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
    Receiving...
    /
    Error making request.
        Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

    Please report this full log at https://github.com/Medium/phantomjs

**Comment by nicks** [comment]
This means your network connection is having problems, please read the FAQ:
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
