### ISSUE TITLE
Phantom installation failed!!

### ISSUE THREAD

**Issue by YonathanB** [Medium/phantomjs#499]
Tried to instal phantomjs and get this error. There is enough space on my disc
![image](https://cloud.githubusercontent.com/assets/4244450/13904895/c3d288c0-eeb8-11e5-9c31-62d6bc515786.png)

**Comment by bluesliverx** [comment]
Looks like you are out of space where it is trying to install it.

**Comment by nicks** [comment]
yep, you need more space on disk
