### ISSUE TITLE
Bitbucket Rate Limit Exceeded

### ISSUE THREAD

**Issue by denodaeus** [Medium/phantomjs#501]
<img width="1274" alt="2016-03-22_1217" src="https://cloud.githubusercontent.com/assets/249286/13958870/1f853e4a-f028-11e5-9b1c-335defbad33e.png">

**Comment by bbergstrom** [comment]
Experiencing same issue.

**Comment by erickrawczyk** [comment]
I am also getting a 429 response code in the middle of my npm install:
```
Error requesting archive.
Status: 429
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/2.14.12 node/v4.2.4 darwin x64"
  },
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie",
  "cache-control": "max-age=900",
  "content-type": "text/plain",
  "strict-transport-security": "max-age=31536000",
  "date": "Tue, 22 Mar 2016 16:35:32 GMT",
  "x-served-by": "app-106",
  "expires": "Tue, 22 Mar 2016 16:35:32 GMT",
  "content-language": "en",
  "etag": "\"62dcd5481fd29816ecc5ae00be2da0b0\"",
  "x-static-version": "d345577559d7",
  "x-render-time": "0.0151710510254",
  "connection": "close",
  "x-request-count": "342",
  "x-frame-options": "SAMEORIGIN",
  "last-modified": "Tue, 22 Mar 2016 16:35:32 GMT",
  "x-version": "d345577559d7",
  "content-length": "46"
}

Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
```

**Comment by aaronjorbin** [comment]
Seeing this on travis as well. https://travis-ci.org/aaronjorbin/develop.wordpress/jobs/117768351

**Comment by aaronjorbin** [comment]
#504 and #505 seem to be duplicates

**Comment by HadesArchitect** [comment]
I can confirm it - the same issue which totally blocks our CI .

**Comment by sandipchitale** [comment]
We are blocked too!

**Comment by gamebox** [comment]
Just to pile on here, also blocked.  Anyone using this in their CI come up with a work-around?

**Comment by EdmundMai** [comment]
Blocked too

**Comment by jayeb** [comment]
@gamebox There are workaround instructions in the project's README: https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs

**Comment by sandipchitale** [comment]
Working again!

**Comment by nicks** [comment]
please read https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs for backup options when bitbucket is down

**Comment by zag2art** [comment]
`export PHANTOMJS_CDNURL=http://cnpmjs.org/downloads `

helped me
