### ISSUE TITLE
403 when getting phantomjs binary

### ISSUE THREAD

**Issue by tardyp** [Medium/phantomjs#506]
```
Found PhantomJS at /usr/bin/phantomjs ...verifying
86PhantomJS detected, but wrong version 1.9.8 @ /usr/bin/phantomjs.
87Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
88Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
89Receiving...
90
91Error requesting archive.
92Status: 403
93Request options: {
94  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
95  "encoding": null,
96  "followRedirect": true,
97  "headers": {
98    "User-Agent": "npm/2.14.20 node/v4.4.0 linux x64"
99  },
100  "strictSSL": false
101}
102Response headers: {
103  "x-amz-request-id": "8B14064AE1BB83C3",
104  "x-amz-id-2": "dUoeYT1jW/k8nY09gEjHFgGcrJsTQHbROja4vlnLtJc7/BvKmSx09NvZ+ti/9EmXdf2NKsW0QCA=",
105  "content-type": "application/xml",
106  "transfer-encoding": "chunked",
107  "date": "Wed, 23 Mar 2016 15:22:16 GMT",
108  "server": "AmazonS3",
109  "connection": "close"
110}
111Make sure your network and proxy settings are correct.
```
If I download manually from "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
I also get an error.

**Comment by tardyp** [comment]
Looks like it was an instability. You can close.

**Comment by limscoder** [comment]
@tardyp we've been experiencing a combination of 403 and 429. I think this may be caused by bitbucket throttling many requests from the same ip range.

We're using the `phantomjs-prebuilt`, so I'm not sure why a 'prebuilt' package needs to checkout source code anyway.

**Comment by nicks** [comment]
please read https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs for backup options when bitbucket is down

**Comment by markushausammann** [comment]
Doesn't sound like this is solved.

**Comment by markushausammann** [comment]
When you do `npm install something` you need it to work, you can't go and fix bitbucket throttling problems and what not.

**Comment by markushausammann** [comment]
I also don't get why it's trying to get it from bitbucket when the releases are on github?

**Comment by markushausammann** [comment]
I see that the newer version don't install from bitbucket anymore... so maybe upgrading will solve the problem.

**Comment by Primajin** [comment]
We have the same issue, running in travis. Every fourth or so build fails, because of 403. Upgrading to a never version, like prebuilt 2.1.7 is currently not possible, since we use casperJS wich does not detect never phantomJS versions correctly.

using `npm install -g phantomjs@2.1.1 --phantomjs_cdnurl=http://cnpmjs.org/downloads` in travis freezes it on 

```shell
Downloading http://cnpmjs.org/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
```

so I guess the cdn does not answer properly. Can you point me to other reliable cdns for that specific version `2.1.1` ?

**Comment by nicks** [comment]
@Primajin can you give more details on how exactly casperjs prevents you from upgrading? If some middleman is blocking phantomjs updates from going out, then I'd like to have a friendly talk with that middleman.

**Comment by Primajin** [comment]
@nicks When using a never version of phantomjs, casperjs will fail with `CasperJS needs PhantomJS v1.x` - so it does not recognize that phantomjs is present - although CasperJS also runs with Phantom 2 since 1.1-beta4 (we are using the newest beta5).

**Comment by alexandru-calinoiu** [comment]
I get a similar error:

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip
Saving to C:\Users\appveyor\AppData\Local\Temp\1\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
 
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "09955213CA930753",
  "x-amz-id-2": "AIN90VzpAXfzx3yuxKYgrxDb8ouac0RFuOBEmbCt8CbzBPGELP4kR4FdmdFxAFVqpEdn5wojpCM=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Mon, 11 Apr 2016 16:09:33 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.
 
If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
```

Is not happening always but 50% of my builds will fail because of it

**Comment by vampolo** [comment]
I do have the same problem as @alexandru-calinoiu . seems like bitbucket is not reliable or they are throttling requests.

**Comment by nicks** [comment]
The newest version of this package does not use bitbucket by default. Please update your package.
