### ISSUE TITLE
npm install phantomjs-prebuilt fails on Jenkins (Linux)

### ISSUE THREAD

**Issue by matthiasbaldi** [Medium/phantomjs#516]
Four days ago the build of an AngularJS Applications works with Jasmine Unittests and Jenkins.
Today it fails with the following error:

```
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /home/jenkins/workspace/jobs/Webapps-bulkedit/workspace/node_modules/phantomjs-prebuilt/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Using proxy http://*********
Receiving...

Received 0K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
] killed: false, code: 2, signal: null } Error: Command failed: bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I think the problem is your change four days ago:
[https://github.com/Medium/phantomjs/commit/2da9622de834b220da4248bc9b2588e6f9736951](https://github.com/Medium/phantomjs/commit/2da9622de834b220da4248bc9b2588e6f9736951)

**Workaround**
When I add the following line to my .npmrc configuration it works:

`phantomjs_cdnurl=https://bitbucket.org/ariya/phantomjs/downloads`

**Comment by nicks** [comment]
hmmmm...it downloaded successfully for me. it looks like you're using a proxy. is there any chance your proxy is blocking github releases? what happens if you `curl https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2` directly on that machine?

**Comment by matthiasbaldi** [comment]
Hey nicks
I think you are right!
We checked it on the console of our Jenkins Server and it won't work there too.
So I think we have to check our proxy configuration or use the Bitbucket link with the cdnurl.
Thank you.
