### ISSUE TITLE
Install failed on ani-theme project with 'npm install' command

### ISSUE THREAD

**Issue by patrickaglibut** [Medium/phantomjs#520]
No idea if this is caused by corporate network error since i'm behind a proxy server or phantomjs. so if this is not phantomjs error please say so. attached also is the npm debug log.

[npm-debug.zip](https://github.com/Medium/phantomjs/files/194922/npm-debug.zip)

D:\github\angular\ani-theme>npm install
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
\
> phantomjs@1.9.19 install D:\github\angular\ani-theme\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\paglibut\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\github\angular\ani-theme\npm-debug.log

**Comment by GrantSchoffelen** [comment]
If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/wu-encrypted/pusherman/products/staffapp/src/npm-debug.log

**Comment by nicks** [comment]
this means that your network is blocked, please read https://github.com/Medium/phantomjs#troubleshooting
