### ISSUE TITLE
Failed at the phantomjs-prebuilt install script

### ISSUE THREAD

**Issue by dodtsair** [Medium/phantomjs#528]
Attempting to install phantomjs-prebuilt fails roughly half the time.  

Here are the steps I take to install:
`
npm install phantomjs-prebuilt@2.1.3
`

Here is the result:
`
+ rm -rf node_modules
+ npm install phantomjs-prebuilt@2.1.3
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})

> phantomjs-prebuilt@2.1.3 install /scratch/jenkins/workspace/phantomjs-prebuilt/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/1.4.21 node/v0.10.30 linux x64"
  },
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "C468CDCF973D76E0",
  "x-amz-id-2": "CdT465Flt+zoCZuDMNTJw4luN5AbkTydfVLRtF6bODVYCPoySe+ouXMr5D0+esb1W9jMRxJK9po=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Fri, 08 Apr 2016 01:04:27 GMT",
  "server": "AmazonS3"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! phantomjs-prebuilt@2.1.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.3 install script.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-71-generic
`

The npm-log file is attached:
[npm-debug.log.txt](https://github.com/Medium/phantomjs/files/209469/npm-debug.log.txt)

**Comment by dodtsair** [comment]
This looks like the same problem as #527 except with phantomjs-prebuilt

**Comment by nicks** [comment]
you should upgrade to 2.1.7, which does not use bitbucket by default
