### ISSUE TITLE
error：when i install angular2 

### ISSUE THREAD

**Issue by q986872053** [Medium/phantomjs#529]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\node_js\\node.exe" "D:\\node_js\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\cordova\angular2-rxjs-chat\npm-debug.log.

so what should i do

**Comment by marcysutton** [comment]
I think you need some more details. Is this part of a seed app?

**Comment by nicks** [comment]
you need to have `node` installed on PATH
