### ISSUE TITLE
Alternative mirror is down

### ISSUE THREAD

**Issue by roydelgado** [Medium/phantomjs#530]
Hello,

The following link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2 is throwing a 404. It was working fine a couple weeks ago.

Any chance you could please upload the file again? Unfortunately, from my end I can't easily switch to another mirror URL.

Thanks!

**Comment by nicks** [comment]
i'm really confused. we have never used that mirror. are you confusing us with another package?

**Comment by roydelgado** [comment]
Got that from your read me: https://github.com/Medium/phantomjs#downloading-from-a-custom-url 
```
Alternatives include https://bitbucket.org/ariya/phantomjs/downloads (the official download site) and http://cnpmjs.org/downloads.
```

**Comment by nicks** [comment]
We've never downloaded 2.0.0 though. We went straight from 1.9.8 to 2.1.1

**Comment by nicks** [comment]
(there is no linux version, and never has been)

**Comment by nicks** [comment]
see https://github.com/ariya/phantomjs/issues/12948 for more information, but a static Linux build of 2.0.0 has never existed, and this package has never tried to install one.

**Comment by roydelgado** [comment]
hmmm that's interesting... from my logs I didn't see this error before so I thought the 404 was the issue.

I'll close this, thanks for your help.
