### ISSUE TITLE
Error happening at Windows 8

### ISSUE THREAD

**Issue by caojinli** [Medium/phantomjs#537]
D:\react\react-redux-starter-kit (master) (react-redux-starter-kit@2.0.0)
λ npm install

> phantomjs-prebuilt@2.1.7 install D:\react\react-redux-starter-kit\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-windows.zip
Saving to D:\MyConfiguration\cjl30804\AppData\Local\Temp\1\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 119.28.3.219:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)

Please report this full log at https://github.com/Medium/phantomjs

**Comment by caojinli** [comment]
Even I disable the symantec Endpoint protection.

**Comment by nicks** [comment]
ETIMEDOUT means that there's an error with your network connection. please read:
https://github.com/Medium/phantomjs#troubleshooting
