### ISSUE TITLE
error installing karma-phantomjs-launcher

### ISSUE THREAD

**Issue by nirajkrz** [Medium/phantomjs#539]
Getting below error when installing.  
PS C:\Projects\PA\pa-ephr-new> npm install --save-dev karma-phantomjs-launcher
npm WARN peerDependencies The peer dependency phantomjs-prebuilt@>=1.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
-
> phantomjs-prebuilt@2.1.7 install C:\Projects\PA\pa-ephr-new\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-windows.zip
Saving to C:\Users\nkumar58\AppData\Local\Temp\1\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [==--------------------------------------] 5%
Error requesting archive.
Status: 403
Request options: {
  "uri": "https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-windows.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/2.14.3 node/v4.1.0 win32 x64"
  },
  "strictSSL": false
}
Response headers: {
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-type": "text/html; charset=utf-8",
  "connection": "close",
  "content-length": "13325"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
tall" "--save-dev" "karma-phantomjs-launcher"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\PA\pa-ephr-new\npm-debug.log

**Comment by patrickliechty** [comment]
I get the same error about 25% of the time in our builds.

**Comment by caojianfeng** [comment]
Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--no-bin-links" "../../"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/caojianfeng/Documents/ovo/thrift/thrift-0.9.3/lib/nodejs/npm-debug.log
make[3]: *** [deps] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by withinboredom** [comment]
This is really annoying and makes the builds highly undependable in a CI environment

**Comment by my2ter** [comment]
Hey,

I have the same error in Scrutinizer-CI. About 20% of my build fail because of that error:

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "E5F8356F41785CDA",
  "x-amz-id-2": "gKuFqYvqqHLoJC5C0OvZgEQZbIEhM6ZKS9VBvCE3rIUrpr2KyZ5nsuiXVKK5B1/77jRKcvz3YCY=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Fri, 03 Jun 2016 03:53:08 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
```

**Comment by nicks** [comment]
please read https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs for options on using alternate mirrors or using phantomjs from disk
