### ISSUE TITLE
Calling the Webpage module inside an express based application

### ISSUE THREAD

**Issue by folivi** [Medium/phantomjs#540]
Hi guys,
I've been trying to use phantomjs to capture parts of a webapp.
Everything works fine when in the terminal when I call my script with phantoms.
Troubles come once I try to use call the same script from my express based application.
`var phantomCaller = childProcess.spawn('phantomjs', [generatorPath]);`
I get the error message:
require('webpage').create() is not a function.
Is there a way to work around this?

Cheers

**Comment by nicks** [comment]
This package is an installer for phantomjs, not support for problems with phantomjs. you're looking for phantomjs.org
