### ISSUE TITLE
Runaway memory usage on v2.1.1+

### ISSUE THREAD

**Issue by ahamid** [Medium/phantomjs#542]
After updating `gulp-mocha-phantomjs` I noticed runaway memory usage.  It appears to be due to the dependency change from

` "phantomjs": "1.9.1 - 1.9.7-15",`
to
`"phantomjs-prebuilt": "^2.1.3",`

There is no `v1.9.7-15` tag, and github claims `v1.9.20` contains `v2.1.1` changes (which I'm confused by).  In any case, reverting the dependency, which results in a `v1.9.20` package appears to fix the runaway memory consumption at end of tests, and leave several lines of (apparently innocuous) output:

```
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///path/to/my/project/base/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js. Domains, protocols and ports must match.
```

```
$ cat /etc/redhat-release 
Fedora release 20 (Heisenbug)
$ uname -a
Linux t440s 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nicks** [comment]
This repo is an installer for phantomjs. You're looking for the main phantomjs project https://github.com/ariya/phantomjs

**Comment by ahamid** [comment]
Oh my apologies!
