### ISSUE TITLE
Getting 403 forbidden when downloading prebuilt phantom 2.1.1

### ISSUE THREAD

**Issue by patrickliechty** [Medium/phantomjs#544]
Today we have received this error 3 times.  Get get the error about 20% of the time in our builds.  We use Electric Commander to do our builds.  Here is the error:

remote:        > phantomjs-prebuilt@2.1.3 install /tmp/build_b941099032e14ee15c76d237a185ca9f/node_modules/phantomjs-prebuilt[K
remote:        > node install.js[K
remote:        [K
remote:        PhantomJS not found on PATH[K
remote:        Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2[K
remote:        Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2[K
remote:        Receiving...[K
remote:        [K
remote:        Error requesting archive.[K
remote:        Status: 403[K
remote:        Request options: {[K
remote:        "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",[K
remote:        "encoding": null,[K
remote:        "followRedirect": true,[K
remote:        "headers": {[K
remote:        "User-Agent": "npm/2.15.1 node/v4.4.4 linux x64"[K
remote:        },[K
remote:        "strictSSL": true[K
remote:        }[K
remote:        Response headers: {[K
remote:        "x-amz-request-id": "F71EE098C93D76C4",[K
remote:        "x-amz-id-2": "wztPujSLhypHxRA/0dawhvc3v5XqVRF/IlJFbGQHUghFbYF2gMgHj/j6MBKLUOn7JsuBSZ6nJ9I=",[K
remote:        "content-type": "application/xml",[K
remote:        "transfer-encoding": "chunked",[K
remote:        "date": "Tue, 10 May 2016 21:37:37 GMT",[K
remote:        "server": "AmazonS3",[K
remote:        "connection": "close"[K
remote:        }[K
remote:        Make sure your network and proxy settings are correct.[K
remote:        [K
remote:        If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs[K
remote:        [K

**Comment by nicks** [comment]
Please upgrade to the latest version, which no longer uses bitbucket
