### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Jun-GitHub** [Medium/phantomjs#546]
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-macosx.zip
Saving to /var/folders/bf/z10zp8yd38zg107ntl95xt4w0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:949:11)
    at TLSWrap.onread (net.js:563:26)

when I used  ' https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip '  to download by browser, it worked. May be there have one more  ' / ' behide  the ' v2.1.1'.

**Comment by nicks** [comment]
This means your network request failed.
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
