### ISSUE TITLE
Binary download contingency option

### ISSUE THREAD

**Issue by mekwall** [Medium/phantomjs#547]
The install script should not immediately fail if the binary download request returns an abnormal response. Packages that depend on phantomjs will fail to install when this happens.

Please implement some kind of contingency option. I suggest adding a limited amount of retries with exponential backoff and/or mirrors for the download.

**Comment by nicks** [comment]
we already do this, plus many configuration options to install from disk or other mirrors
https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs
