### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by MRKiscaden** [Medium/phantomjs#549]
I have a vagrant image I am trying to set up to use PhantomJS, I don't know much about phantom, so I have no idea what is causing this issue:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "phantomjs-prebuilt"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.

[npm-debug.zip](https://github.com/Medium/phantomjs/files/282609/npm-debug.zip)

**Comment by nicks** [comment]
please read:
https://github.com/Medium/phantomjs#installation-fails-with-spawn-enoent

you probably don't have node installed on PATH
