### ISSUE TITLE
error phantomjs-prebuilt@2.1.7 install: `node install.js`

### ISSUE THREAD

**Issue by wuxiaolan91** [Medium/phantomjs#556]
4760 silly install phantomjs-prebuilt@2.1.7 /www/kaye_4.0/node_modules/.staging/phantomjs-prebuilt-e1d1b92a
4761 info lifecycle phantomjs-prebuilt@2.1.7~install: phantomjs-prebuilt@2.1.7
4762 verbose lifecycle phantomjs-prebuilt@2.1.7~install: unsafe-perm in lifecycle false
4763 verbose lifecycle phantomjs-prebuilt@2.1.7~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/www/kaye_4.0/node_modules/phantomjs-prebuilt/node_modules/.bin:/www/kaye_4.0/node_modules/.bin:/usr/bin:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/jre/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root:/usr/local/node-v4.2.2-linux-x64/bin:/root/bin
4764 verbose lifecycle phantomjs-prebuilt@2.1.7~install: CWD: /www/kaye_4.0/node_modules/phantomjs-prebuilt
4765 silly lifecycle phantomjs-prebuilt@2.1.7~install: Args: [ '-c', 'node install.js' ]
4766 silly lifecycle phantomjs-prebuilt@2.1.7~install: Returned: code: 1  signal: null
4767 info lifecycle phantomjs-prebuilt@2.1.7~install: Failed to exec install script
4768 verbose unlock done using /root/.npm/_locks/staging-6af443226cc00fc2.lock for /www/kaye_4.0/node_modules/.staging
4769 silly rollbackFailedOptional Starting
4770 silly rollbackFailedOptional Finishing
4771 silly runTopLevelLifecycles Starting
4772 silly runTopLevelLifecycles Finishing
4773 silly install printInstalled
4774 warn optional Skipping failed optional dependency /chokidar/fsevents:
4775 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
4776 verbose stack Error: phantomjs-prebuilt@2.1.7 install: `node install.js`
4776 verbose stack Exit status 1
4776 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
4776 verbose stack     at emitTwo (events.js:100:13)
4776 verbose stack     at EventEmitter.emit (events.js:185:7)
4776 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
4776 verbose stack     at emitTwo (events.js:100:13)
4776 verbose stack     at ChildProcess.emit (events.js:185:7)
4776 verbose stack     at maybeClose (internal/child_process.js:850:16)
4776 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
4777 verbose pkgid phantomjs-prebuilt@2.1.7
4778 verbose cwd /www/kaye_4.0
4779 error Linux 2.6.32-431.23.3.el6.x86_64
4780 error argv "/usr/bin/node" "/usr/bin/npm" "install"
4781 error node v5.11.1
4782 error npm  v3.8.6
4783 error code ELIFECYCLE
4784 error phantomjs-prebuilt@2.1.7 install: `node install.js`
4784 error Exit status 1
4785 error Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
4785 error Make sure you have the latest version of node.js and npm installed.
4785 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
4785 error not with npm itself.
4785 error Tell the author that this fails on your system:
4785 error     node install.js
4785 error You can get information on how to open an issue for this project with:
4785 error     npm bugs phantomjs-prebuilt
4785 error Or if that isn't available, you can get their info via:
4785 error     npm owner ls phantomjs-prebuilt
4785 error There is likely additional logging output above.
4786 verbose exit [ 1, true ]

**Comment by xiaoyi001yeye** [comment]
最好咋解决的？

**Comment by cadavre** [comment]
+1

**Comment by nicks** [comment]
this indicates you don't have node installed. please read the troubleshooting guide.
https://github.com/Medium/phantomjs#troubleshooting

**Comment by Igor912** [comment]
I have the same issue with Node version 8.1.2(new) and npm version 5.0.3.
After I downgraded Node to V6.11.0(stable) and npm V3.10.10 it fixed my issue.
