### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lzliu** [Medium/phantomjs#559]
when npm install  "react-redux-universal-hot-example-master" , get following error:

> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phanto
mjs-1.9.8-windows.zip
Saving to C:\Users\ADMINI~1\AppData\Local\Temp\1\phantomjs\phantomjs-1.9.8-windo
ws.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\R\r-u\npm-debug.log

**Comment by kozie** [comment]
I have exactly the same problem on a Ubuntu 12.04, 64bit machine. I have the latest version of node installed (6.x) and also tried it using 4.x. I got both the Node and Nodejs commands so that shouldn't be the problem for me, i guess.

**Comment by meticulo3366** [comment]
same issue i cannot install phantom js

2016-06-23T04:15:55.123ZError requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "FCA115EAD4937B63",
  "x-amz-id-2": "YUEHHnonKC0vPjkJggjFWVfnVnOdAWeXKj8da9rfEGthyu+Uul4EgAAxA7fllW5ygYCz+Bz1Mvc=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Thu, 23 Jun 2016 04:15:54 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs

**Comment by kozie** [comment]
I don't think it has something to do with network or any other connection settings as it seems to fail to run a command, namely `node install.js`.

I could be wrong tho..

**Comment by nicks** [comment]
ECONNRESET indicates a problem with your network. please read: 
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout
and the other troubleshooting docs

**Comment by kevincream** [comment]
I still have the same error, without ECONNRESET so it seems it indeed isn't a connection problem.

I had the following logged
```
npm ERR! Linux 3.2.0-104-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
```

**Comment by kozie** [comment]
Yeah, that's what i thought. Can this be re-opened?

**Comment by kozie** [comment]
This is becoming quite annoying now. We can't quite continue with the frontend side. We're working with the following package.json. Everything, and i mean, everything seems to work just fine, except for the phantomjs install. As said before, it doesn't seem to be a network problem.

Please re-open this issue and take a look again, if you don't mind.

```
{
  "name": "Magento2",
  "author": "Magento Commerce Inc.",
  "description": "Magento2 node modules dependencies for local development",
  "version": "2.0.0",
  "license": "(OSL-3.0 OR AFL-3.0)",
  "repository": {
    "type": "git",
    "url": "https://github.com/magento/magento2.git"
  },
  "homepage": "http://magento.com/",
  "devDependencies": {
    "glob": "^5.0.14",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^2.0.0",
    "grunt-banner": "^0.4.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jasmine": "^0.8.1",
    "grunt-contrib-less": "^0.12.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-eslint": "17.3.1",
    "grunt-exec": "^0.4.6",
    "grunt-jscs": "2.2.0",
    "grunt-replace": "^0.9.2",
    "grunt-styledocco": "^0.1.4",
    "grunt-template-jasmine-requirejs": "^0.2.3",
    "grunt-text-replace": "^0.4.0",
    "imagemin-svgo": "^4.0.1",
    "load-grunt-config": "^0.16.0",
    "morgan": "^1.5.0",
    "node-minify": "^1.0.1",
    "path": "^0.11.14",
    "serve-static": "^1.7.1",
    "strip-json-comments": "^1.0.2",
    "time-grunt": "^1.0.0",
    "underscore": "^1.7.0"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

**Comment by lzliu** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  I don't think it is communication issue either. I star mom install three projects only one has the issue, which may mean only the one involves phantomjs got the problem. If there is communication problem all 3 should fail, but it is not the case.
Please reopen it and check again.

Thanks.


Sent from Yahoo Mail for iPad


On Wednesday, June 29, 2016, 2:46 AM, Kozie <notifications@github.com> wrote:


This is becoming quite annoying now. We can't quite continue with the frontend side. We're working with the following package.json. Everything, and i mean, everything seems to work just fine, except for the phantomjs install. As said before, it doesn't seem to be a network problem.

Please re-open this issue and take a look again, if you don't mind.case.
{
  "name": "Magento2",
  "author": "Magento Commerce Inc.",
  "description": "Magento2 node modules dependencies for local development",
  "version": "2.0.0",
  "license": "(OSL-3.0 OR AFL-3.0)",
  "repository": {
    "type": "git",
    "url": "https://github.com/magento/magento2.git"
  },
  "homepage": "http://magento.com/",
  "devDependencies": {
    "glob": "^5.0.14",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^2.0.0", 
    "grunt-banner": "^0.4.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jasmine": "^0.8.1",
    "grunt-contrib-less": "^0.12.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-eslint": "17.3.1",
    "grunt-exec": "^0.4.6",
    "grunt-jscs": "2.2.0",
    "grunt-replace": "^0.9.2",
    "grunt-styledocco": "^0.1.4",
    "grunt-template-jasmine-requirejs": "^0.2.3",
    "grunt-text-replace": "^0.4.0",
    "imagemin-svgo": "^4.0.1",
    "load-grunt-config": "^0.16.0",
    "morgan": "^1.5.0",
    "node-minify": "^1.0.1",
    "path": "^0.11.14",
    "serve-static": "^1.7.1",
    "strip-json-comments": "^1.0.2",
    "time-grunt": "^1.0.0",
    "underscore": "^1.7.0"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
