### ISSUE TITLE
Cant Download phantomjs-1.9.8-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by meticulo3366** [Medium/phantomjs#560]
2016-06-23T04:15:55.123ZError requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "x-amz-request-id": "FCA115EAD4937B63",
  "x-amz-id-2": "YUEHHnonKC0vPjkJggjFWVfnVnOdAWeXKj8da9rfEGthyu+Uul4EgAAxA7fllW5ygYCz+Bz1Mvc=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Thu, 23 Jun 2016 04:15:54 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs

**Comment by nicks** [comment]
you need to upgrade to a newer version. we no longer download from bitbucket
