### ISSUE TITLE
Phantomjs stall on webpack build

### ISSUE THREAD

**Issue by track0x1** [Medium/phantomjs#562]
When PhantomJS uses webpack to build before running any tests, when it fails to find a file it stalls. This is causing issues on my build server which is hanging until I manually kill it.

`
12:02:23.598 Module not found: Error: Cannot resolve 'file' or 'directory' ...
`

Is there any solution to this? I already have `bail: true` in my webpack config for karma.

**Comment by nicks** [comment]
i think you're confused, this installer doesn't use webpack
