### ISSUE TITLE
Linux prebuild rasterizes pdf

### ISSUE THREAD

**Issue by iptaylortechnical** [Medium/phantomjs#564]
Using the html-pdf library (https://github.com/marcbachmann/node-html-pdf) on OS X, pdfs are created and sent to the browser correctly. However, once we deploy, all of our pdfs come out rasterized (aka 12 times bigger file size). We're pretty sure we've narrowed it down to the difference between OS X phantom prebuilt and Linux phantom prebuilt.

Linux prebuilt exhibiting this behavior is 2.1.1.

**Comment by marcbachmann** [comment]
That issue would belong into https://github.com/ariya/phantomjs.
There's already an issue for it: https://github.com/ariya/phantomjs/issues/13997
