### ISSUE TITLE
 PhantomJS detected, but wrong version

### ISSUE THREAD

**Issue by ayappanec** [Medium/phantomjs#567]
I am building tez 0.7.0 in ppc64le. Maven while building the tez-ui module gets phantomjs through the npm uitlity But since the binay for ppc64le is not available, i manually built phantomjs locally and installed it. But there seems to be mismatch in the version. 

[INFO] (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
[INFO] Considering PhantomJS found at /usr/bin/phantomjs
[INFO] Found PhantomJS at /usr/bin/phantomjs ...verifying
**[INFO] PhantomJS detected, but wrong version 2.1.1 @ /usr/bin/phantomjs.**
[INFO] Unexpected platform or architecture: linux/ppc64
[INFO] It seems there is no binary available for your platform/architecture
[INFO] Try to install PhantomJS globally
[INFO] npm ERR! weird error 1
[INFO] npm ERR! not ok code 0

I built 2.1.1 version whereas the npm checks for 1.9.20 version (phantomjs-prebuilt) which inturn has phantomjs 1.9.8 binary .I searched in the entire code to find out the "1.9.20" or "1.9.8". No hits!! . Not sure where can i modify the version so that it goes ahead with the 2.1.1 version.
Can you guys help here ?

**Comment by nicks** [comment]
It looks like tez sets their phantomjs version here:
https://github.com/apache/tez/blob/2c22e23a738a7764aa8d53ca7e2bcba7d7053337/tez-ui/src/main/webapp/package.json#L57

you'll need to ask them to upgrade it, or build 1.9.8

**Comment by ayappanec** [comment]
The link refers to the master branch. I am building the 0.7.0 version where there is no phantomjs keyword in the entire source code. 

https://github.com/apache/tez/blob/release-0.7.0/tez-ui/src/main/webapp/package.json
