### ISSUE TITLE
Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'

### ISSUE THREAD

**Issue by techswa** [Medium/phantomjs#568]
Just following instructions to report the full log.  Since I didn't see anywhere specific to paste I have included it below:

npm install -g phantomjs-prebuilt
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.7 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Error checking path, continuing { [Error: Cannot find module '/usr/local/lib/node_modules/phantomjs-prebuilt/lib/location'] code: 'MODULE_NOT_FOUND' }
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-macosx.zip
Saving to /var/folders/31/41k8x2fx1lq_8c9f0_g1fgt40000gp/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [=============================-----------] 73%
Error making request.
Error: read ETIMEDOUT
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "phantomjs-prebuilt"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/swa/Documents/Dev/ember/npm-debug.log

**Comment by mbotellos** [comment]
Try this: https://www.npmjs.com/package/phantomjs#downloading-from-a-custom-url, it works for me.

**Comment by nicks** [comment]
https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout

**Comment by jesponde** [comment]
I have the same issue and the solution is described here:
https://github.com/Medium/phantomjs#im-on-debian-or-ubuntu-and-the-installer-failed-because-it-couldnt-find-node
This package conflict is unfortunate... debian based distros are quite common...

**Comment by Igor912** [comment]
I have the same issue with Node version 8.1.2(new) and npm version 5.0.3.
After I downgraded Node to V6.11.0(stable) and npm V3.10.10 it fixed my issue.

**Comment by kekstlt** [comment]
Check that bzip2 installed
Installator trying to extract an package

# yum install bzip2
