### ISSUE TITLE
PhantomJS-prebuilt package for linux/arm64

### ISSUE THREAD

**Issue by ricadelic** [Medium/phantomjs#577]
Hi,

it would be really nice to have the package supporting ARM64. Even when i build the phantomJS library myself, i cannot use it as the install.js package reports it cannot install on linux/arm64.

As you can see below, i've made sure PhantomJS (2.2.0) reports it's version as 2.1.7.

odroid@odroid64:~$ npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.8 install /home/odroid/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.7 @ /usr/bin/phantomjs.
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN enoent ENOENT: no such file or directory, open '/home/odroid/package.json'
npm WARN odroid No description
npm WARN odroid No repository field.
npm WARN odroid No README data
npm WARN odroid No license field.
npm ERR! Linux 3.14.65-72
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantomjs-prebuilt"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.8 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.8 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/odroid/npm-debug.log

odroid@odroid64:~$ /usr/bin/phantomjs --version
2.1.7

odroid@odroid64:~$ uname -r
3.14.65-72
odroid@odroid64:~$ uname -a
Linux odroid64 3.14.65-72 #1 SMP PREEMPT Wed Jul 20 21:51:35 BRT 2016 aarch64 aarch64 aarch64 GNU/Linux
odroid@odroid64:~$

**Comment by nicks** [comment]
the most recent phantomjs version is 2.1.1 (http://phantomjs.org/download.html), where are you getting 2.1.7?

**Comment by nicks** [comment]
closing this, as this appears to be correct behavior. the phantomjs you built is reporting a weird version.

**Comment by karneaud** [comment]
is there any arm64 version of phantomjs?

**Comment by ricadelic** [comment]
You should be able to build it yourself
