### ISSUE TITLE
not recognizing arm64.

### ISSUE THREAD

**Issue by ganeshrajuLinaro** [Medium/phantomjs#579]
getting the following error, when i do 

> npm i -g phantomjs-prebuilt

/home/ganesh.raju/node/bin/phantomjs -> /home/ganesh.raju/node/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.8 install /home/ganesh.raju/node/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /home/ganesh.raju/node/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
**Unexpected platform or architecture: linux/arm64**
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/home/ganesh.raju/node/bin/node" "/home/ganesh.raju/node/bin/npm" "i" "-g" "phantomjs-prebuilt"
npm ERR! node v4.2.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.8 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.8 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ganesh.raju/npm-debug.log

**Comment by nicks** [comment]
correct, there is no prebuilt-binary available for linux/arm64, so there's nothing for us to install. I added an FAQ to the guide about this. https://github.com/Medium/phantomjs#im-using-an-unsupported-version-of-linux-or-an-arm-processor-i-get-errors-about-unexpected-platform-or-architecture-what-do-i-do
