### ISSUE TITLE
bundledDependencies is producing a long path under node_modules

### ISSUE THREAD

**Issue by siirila** [Medium/phantomjs#589]
The bundledDependencies are producing a long path length that can cause problems on Windows if the path before the node_modules folder is ~70 characters long.

It looks like the change for  #585 is resulting in the node_modules folder not being deduped, probably since this appears to be build with npm version 2.15.1, which can cause problems on Windows. Installing the package in a folder name with a single character, such as C:\I, on Windows still results in a path length for the longest path in the node_modules folder of 192 characters. It is easy to exceed the 260 character file path limit as a result, which can cause unexpected behavior.

**Comment by rmg** [comment]
Good catch. Publishing with bundled deps is definitely something that is ideally done with npm@3. I hope @nicks doesn't mind the extra hurdle this requires.

**Comment by nicks** [comment]
Ya will do just going to wait for some other PRs to roll in

**Comment by siirila** [comment]
Awesome. Thanks for being so responsive. As an alternative, I looked around a little and it seems like if the nested dependencies were listed in the bundledDependencies list and dedupe was run with npm 2 it should also produce a flattened dependency tree.

I can give that a shot and submit a pull request if you would like, but I wasn't sure if it would produce a different set of dependencies based on the platform.

**Comment by hem19** [comment]
even after taking v2.1.10, nested node_modules are getting created and is causing 260 character limit issue in windows

**Comment by nicks** [comment]
try 2.1.11. TIL that bundledDependencies is a minefield of undocumented assumptions

**Comment by nicks** [comment]
ya, seems fine in the latest version.
