### ISSUE TITLE
'phantomjs-prebuilt/node_modules' folder is removed after a second 'npm install'

### ISSUE THREAD

**Issue by brunogarcia** [Medium/phantomjs#591]
Hi,

We've found a very weird bug with `phantomjs-prebuilt@2.1.9`.
These are the steps for reproduce the problem:

- First 'npm install' -> all dependencies installed correctly.
- Second 'npm install' -> `/my_app/node_modules/phantomjs-prebuilt/node_modules/` folder is removed (around 100 packages)
- Third 'npm install' ->  `npm ERR! enoent ENOENT: no such file or directory, chmod '/my_app/node_modules/phantomjs-prebuilt/node_modules/extract-zip/node_modules/mkdirp/bin/cmd.js'`

OS: Linux Ubuntu 16.04/14.0, Centos 7.2
Node: 5.2.0
NPM: 3.3.12

**Comment by nicks** [comment]
i was not able to reproduce this in the latest version
