### ISSUE TITLE
so many nested node_modules folder causing max character length issue in windows

### ISSUE THREAD

**Issue by hem19** [Medium/phantomjs#597]
I saw that you mentioned in v2.1.10 nested paths issue has been resolved and it is built using NPM3. But still when I tried to install using 'npm install phantomjs-prebuilt', I can see so many nested node_modules folder. (e.g. "node_modules\phantomjs-prebuilt\node_modules\fs-extra\node_modules\rimraf\node_modules\glob\node_modules")
This again is causing the error of max character length of 260 in windows.

I am using 'Karma' for unit tests in my automated nightly builds, but I am getting max character length error and builds are failing.

Could you please let me know if there is any release which don't have nested folder structure.

Thanks

**Comment by joeldejong** [comment]
We're experiencing the same issue. Could you please fix this?

Thanks

**Comment by nicks** [comment]
dupe #589
