### ISSUE TITLE
Breaking Changes and SemVer

### ISSUE THREAD

**Issue by eddiemonge** [Medium/phantomjs#604]
There have been a few releases with breaking changes that have not had the correct semver versions attached. As an example, 2.1.12 is a breaking change since it changes how things are installed. Things that depended on the bundledDependencies will now break.

**Comment by nicks** [comment]
I was told that the bundledDependencies change was a bugfix pr that would maintain compatibility. As it turned out, the change was highly problematic and non-portable across different NPM versions. The change has been rolled back, and will not be rolled forward.
