### ISSUE TITLE
Installation failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by geostant** [Medium/phantomjs#630]
Docker container based on ubuntu 16.04 + NodeJS 6.x and NGINX
Get the following error:

>    Error extracting archive
>    Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
>    tar (child): bzip2: Cannot exec: No such file or directory
>    tar (child): Error is not recoverable: exiting now
>    tar: Child returned status 2
>    tar: Error is not recoverable: exiting now

>   at ChildProcess.exithandler (child_process.js:206:12)
>   at emitTwo (events.js:106:13)
>   at ChildProcess.emit (events.js:191:7)
>   at maybeClose (internal/child_process.js:877:16)
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>  killed: false,
>  code: 2,
>  signal: null,
>  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
>   tar (child): bzip2: Cannot exec: No such file or directory
>   tar (child): Error is not recoverable: exiting now
>   tar: Child returned status 2
>   tar: Error is not recoverable: exiting now

>   at ChildProcess.exithandler (child_process.js:206:12)
>   at emitTwo (events.js:106:13)
>   at ChildProcess.emit (events.js:191:7)
>   at maybeClose (internal/child_process.js:877:16)
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

which node = /usr/bin/node
and 
which tar = /bin/tar

**Comment by nicks** [comment]
you need to install bzip2
