### ISSUE TITLE
Error making request. Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by kevincaradant** [Medium/phantomjs#631]
Hi

Do you have any idea, how can I solve this problem properly ? 
I read somewhare something about ca keys ? 
Have I to create this ? 

Thank you 

code:
```
Saving to C:\Users\XX\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
```

**Comment by kevincaradant** [comment]
ok I fixed it with: `npm set strict-ssl false = false`, I'm not sure it's really a solution but it's at least a workaround. If you have a better way. i'm listening :)

**Comment by novascreen** [comment]
I have the same issue, I actually provided a certificate file to npm with the `cafile` option and all other npm operations work fine, but this fails. I don't think `strict-ssl=false` is the solution here.

**Comment by traviskeenan** [comment]
My issue ended up being a local proxy agent that was blocking the request.

**Comment by bashisha** [comment]
I am getting the following error when ionic start.
PS C:\Users\Downloads> ionic start myApp tabs
[WARN] Git CLI not found on your PATH. You may wish to install it to version control your app.
       See installation docs for git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

       Use --no-git to disable this warning.

[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✖ Downloading - failed!
Error: unable to get local issuer certificate

**Comment by pinich** [comment]
Is there any solution for this error ?
`npm set strict-ssl false = false`
Not fixed this issue for me
