### ISSUE TITLE
PhantomJS 1.x not on NPM?

### ISSUE THREAD

**Issue by walterdolce** [Medium/phantomjs#633]
Hi, looks like only versions 2.x of the tool are available on NPM.
Where can 1.x releases be downloaded from? Doesn't seem they are available [on the NPM repository](https://registry.npmjs.org/phantomjs-prebuilt/).

Given the 2.x release series seem to have introduced [something which breaks for many people](https://github.com/ariya/phantomjs/issues/14257) ([as it doesn't properly inject an object and lacks object property existence checks](https://github.com/ariya/phantomjs/blob/master/src/ghostdriver/hub_register.js#L36)), I wanted to follow your suggestion of pulling `phantomjs-prebuilt` instead of `phantomjs` but by using some of the 1.x releases. But I can't.

Thank you.

**Comment by JuanCaicedo** [comment]
I think the name of this project used to be `phantomjs` you can find the older versions using that name.

```
npm show phantomjs@* version
```
