### ISSUE TITLE
Cannot run pre-built phantomjs on Ubuntu 16.04 in Vagrant

### ISSUE THREAD

**Issue by z4y4ts** [Medium/phantomjs#637]
First of all I got to tell you that running phantomjs on a headless Ubuntu seems to be just impossible at the time. I've tried 3 different methods and none of them resulted in working phantomjs. But let's start with official way to install it.

So I've installed phantomjs from [here](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2) and also installed libfontconfig from the apt repos.

> This application failed to start because it could not find or load the Qt platform plugin "offscreen".
> 
> Available platform plugins are: phantom.
> 
> Reinstalling the application may fix this problem.
> PhantomJS has crashed. Please read the bug reporting guide at
> <http://phantomjs.org/bug-reporting.html> and file a bug report.
> Aborted (core dumped)

Any ideas where to move from here?

**Comment by nicks** [comment]
This repo is an npm installer. You're looking for https://github.com/ariya/phantomjs
