### ISSUE TITLE
Need to update url for older versions of phantomjs?

### ISSUE THREAD

**Issue by snakescott** [Medium/phantomjs#639]
phantomjs@1.9.2-6 install /usr/local/lib/node_modules/phantomjs
> node install.js
Looks like an `npm install -g`; unable to check for already installed version.
Downloading http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2

http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2 404s

The new url may be
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2

**Comment by nicks** [comment]
ya, googlecode shut down. we don't plan on going back to fix arbitrarily old versions. please upgrade to the latest version
