### ISSUE TITLE
Different paths for OSX and Linux executables

### ISSUE THREAD

**Issue by geekdave** [Medium/phantomjs#64]
Hello and thanks for this fantastic project!

We are using phantomjs for a large enterprise project with dozens of developers.  Rather than have every developer maintain their own npm dependencies, we have our `node_modules` directory checked-in under source control.  This way, developers can pull from the repo, run `grunt` and everything "just works".

The issue is that we support multiple development environments.  We have developers using Windows, Mac OSX, and Linux.  Most of our grunt dependencies are platform-agnostic.  However, since phantom has different binary executables for these three platforms, we need to have the superset of all three binaries checked in.  

So far we have:

For Windows, we checked in:
`lib/phantom/phantomjs.exe`

For Mac OSX, we checked in:
`lib/phantom/bin/phantomjs`

We tried to do the same for Linux, but found that the path & filename for the Linux binary are the same as for Mac OSX.

Sure enough, in `lib/phantomjs.js` there is only a differentiation made between windows and "everything else"

``` js
exports.path = process.platform === 'win32' ?
    path.join(__dirname, 'phantom', 'phantomjs.exe') :
    path.join(__dirname, 'phantom', 'bin' ,'phantomjs')
```

What if we added platform-specific subdirectories in `lib/phantom`, and then changed the above snippet to:

``` js
switch (process.platform) {
  case 'win32':
    exports.path = path.join(__dirname, 'phantom', 'win', 'phantomjs.exe');
    break;
  case 'darwin':
    exports.path = path.join(__dirname, 'phantom', 'mac', 'phantomjs');
    break;
  case 'linux':
  default:
    exports.path = path.join(__dirname, 'phantom', 'linux', 'phantomjs');
    break;
}
```

This would allow us to check-in platform-specific binaries like:

```
lib/phantom/win32/phantomjs.exe
lib/phantom/mac/phantomjs
lib/phantom/linux/phantomjs
```

Thanks!

**Comment by stratoeric** [comment]
We have the same issue here and I wonder if the changes in the installer as mentioned above are everything I have to adapt - besides the location.js file of course. But then, I have to patch the location.js file depending on which system I am?! @geekdave

**Comment by jchitel** [comment]
I'd like to see this re-opened too. There are plenty of use cases for this, and npm packages are implied to be platform independent. If there is a file included that is platform-dependent, it should be placed on a special path so that rebuilding on another machine doesn't clobber the existing binary.

**Comment by nicks** [comment]
re: `npm packages are implied to be platform independent`: This is simply not true. Many node packages have native code. 

The standard solution these days is to run `npm rebuild` to ensure platform-specific dependencies are correct. see:
https://github.com/Medium/phantomjs#cross-platform-repositories
