### ISSUE TITLE
 Failed at the phantomjs@1.9.20 install script 'node install.js'

### ISSUE THREAD

**Issue by hibumbapartha** [Medium/phantomjs#644]
When I run 

> npm install

From the following [angular-seed](https://github.com/mgechev/angular-seed)

I got following error log.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\c
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\g
lp-watch\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64
})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     P:\Users\VC28755\Documents\codebase-git\angular-seed\npm-debug.log

**Comment by Enkrod** [comment]
I'm running into the same problem, but on a different route:

I've installed bootstrap via npm and would like to use its Gruntfile.js but it wants to install the grunt-contrib-qunit and fails on the dependency phantomjs.

I get the following error.

C:\Users\s.wolfertz\PhpstormProjects\ammeilenstein\node_modules\bootstrap>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

phantomjs@1.9.20 install C:\Users\s.wolfertz\PhpstormProjects\ammeilenstein\node_modules\bootstrap\node_modules\grunt-contrib-qunit\node_modules\grunt-lib-phantomjs\node_modules\phantomjs
node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-windows.zip
Saving to C:\Users\S624D~1.WOL\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Using proxy http://192.168.20.13:8080/
Using npmconf ca
Receiving...

Error making request.
Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\s.wolfertz\PhpstormProjects\ammeilenstein\node_modules\bootstrap\npm-debug.log


[npm-debug.log.txt](https://github.com/Medium/phantomjs/files/626677/npm-debug.log.txt)

**Comment by arangelp** [comment]
I am having exactly the same issue

**Comment by galtenhofen** [comment]
Same here.


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\PrelimReport\npm-debug.log
npm ERR! code 1

**Comment by audduk** [comment]
Thanks @galtenhofen, 

npm set strict-ssl false 

works!

**Comment by Eugene1982** [comment]
It works! Thanks!

**Comment by cash1981** [comment]
I have the same problem, however npm set strict-ssl false did not work for me :-1: 

Can you open this issue again?

**Comment by MuthuAliasKumar** [comment]
am also facing the same issue...  strict-ssl false is false already... please open this issue

**Comment by elfeck** [comment]
Same Issue!

**Comment by itaiif** [comment]
same..

**Comment by novokrest** [comment]
same

**Comment by novokrest** [comment]
I had the same problem on Windows and solved it by running command line in **Administrator mode** and issuing _npm set strict-ssl false_ (as  @galtenhofen mentioned) before _npm install_

**Comment by SaeedHassanvand** [comment]
I have the same problem!!! even after npm  install set strict-ssl false

**Comment by Enkrod** [comment]
@SaeedHassanvand try "npm set strict-ssl false"

(without install)

**Comment by tsekityam** [comment]
I had this problem when I ran `npm install` in Bash on Ubuntu on Windows, and I found the solution of it.

# TL;DR
`$ sudo apt install nodejs-legacy`

# Detail
Here is the error log when I ran `npm install`:
```
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/dev/angular-bing-maps/npm-debug.log
```

I executed `node install.js` and I got the following error:
```
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

So I ran `sudo apt install nodejs-legacy` to install program 'node'. After installation, `npm install` can be completed without any error.

**Comment by VenkateshManohar27** [comment]
Thanks @galtenhofen,

npm set strict-ssl false

works for me

**Comment by carlosonunez** [comment]
Setting SSL to false is not a solution.

**Comment by vijjukumar** [comment]
what's the solution still i am getting the same error after setting npm set strict-ssl false and running as Administrator. please give your inputs. Thanks
