### ISSUE TITLE
Cannot find module 'pend'

### ISSUE THREAD

**Issue by murieletrentini** [Medium/phantomjs#645]
Hi. I've tried to install markdown-pdf and run into an error with phantomjs in the process.
Im running
  node: v6.9.1
  npm: v3.10.8

here the error-log:
npm install markdown-pdf --save

> phantomjs-prebuilt@2.1.13 install /path/to/project/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'pend'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/project/node_modules/fd-slicer/index.js:7:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
markdown@0.0.0 /path/to/project
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "markdown-pdf" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

**Comment by nicks** [comment]
Hmmm...this project doesn't even depend on `pend` or `fd-slicer`. The `npm` blame message is buggy, and the problem is likely caused by something else in your package.json. You should file a bug against npm
