### ISSUE TITLE
Install fails on NPM

### ISSUE THREAD

**Issue by christill** [Medium/phantomjs#656]
Hi,

I'm unable to install this package via NPM for the last couple of days.

NPM is just not installing that package. On my jenkins box i'm getting no warning or error, it just stops.

Locally, I'm now seeing `PhantomJS not found on PATH`

**Comment by Ha-Sch** [comment]
Hi,

i'm unable to install this package via NPM on windows 7 too. 
"Failed at the phantomjs@1.9.20 install script 'node install.js'.
 Make sure you have the latest version of node.js and npm installed.
 If you do, this is most likely a problem with the phantomjs package,
 not with npm itself."
