### ISSUE TITLE
Failed at the phantomjs@1.9.20 install script 'node install.js'

### ISSUE THREAD

**Issue by cash1981** [Medium/phantomjs#676]
I have the exact same problem as issue #644 

However, `npm set strict-ssl false` did not work for me
I still get the same problem when I run `npm install`

Here is the output from npm install

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: node install.js
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.

_Here is the npm-debug.log file_

9494 verbose stack Error: phantomjs@1.9.20 install: node install.js
9494 verbose stack spawn ENOENT
9494 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
9494 verbose stack     at emitTwo (events.js:87:13)
9494 verbose stack     at ChildProcess.emit (events.js:172:7)
9494 verbose stack     at maybeClose (internal/child_process.js:821:16)
9494 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9495 verbose pkgid phantomjs@1.9.20
9496 verbose cwd /home/shervin/workspace/civilization-boardgame-web
9497 error Linux 4.4.0-64-generic
9498 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
9499 error node v4.2.6
9500 error npm  v3.5.2
9501 error file sh
9502 error code ELIFECYCLE
9503 error errno ENOENT
9504 error syscall spawn
9505 error phantomjs@1.9.20 install: node install.js
9505 error spawn ENOENT
9506 error Failed at the phantomjs@1.9.20 install script node install.js

**Comment by jameswomack** [comment]
I'm experiencing the same

**Comment by gvinson** [comment]
Same

**Comment by jrdespai** [comment]
I'm having this issue too, it looks like this actually might be related to an AWS outage (look at the bottom of this issue): #674

**Comment by diegoconcha** [comment]
I was able to get this working via:
https://github.com/Medium/phantomjs/issues/674#issuecomment-283150753

**Comment by sudhirpal** [comment]
May I know when this issue gets resolved? I tried just now but still seeing the same problem.

**Comment by cash1981** [comment]
Can anyone verify that this bug is still there? Perhaps it was the amazon aws outage

**Comment by sudhirpal** [comment]
After couple of hours it worked for me.  And I'm not seeing this issue anymore. Thanks!

**Comment by cash1981** [comment]
I upgrade npm as it suggested, and now it worked

**Comment by bashisha** [comment]
how did you upgraded npm?
