### ISSUE TITLE
npm install fails with Error: phantomjs-prebuilt@2.1.14 install: `node install.js`

### ISSUE THREAD

**Issue by tovinayv** [Medium/phantomjs#685]
126039 verbose stack Error: phantomjs-prebuilt@2.1.14 install: `node install.js`
126039 verbose stack spawn sh ENOENT
126039 verbose stack     at exports._errnoException (util.js:1028:11)
126039 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
126039 verbose stack     at onErrorNT (internal/child_process.js:359:16)
126039 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
126039 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
126040 verbose pkgid phantomjs-prebuilt@2.1.14
126041 verbose cwd /build/mts/release/sb-8997652/vrops-vcd-tenant-view
126042 error Linux 2.6.18-308.8.1.el5
126043 error argv "/build/mts/release/sb-8997652/vrops-vcd-tenant-view/node/node" "/build/mts/release/sb-8997652/vrops-vcd-tenant-view/node/node_modules/npm/bin/npm-cli.js" "install"
126044 error node v7.6.0
126045 error npm  v4.1.2
126046 error file sh
126047 error path sh
126048 error code ELIFECYCLE
126049 error errno ENOENT
126050 error syscall spawn sh
126051 error phantomjs-prebuilt@2.1.14 install: `node install.js`
126051 error spawn sh ENOENT
126052 error Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
126052 error Make sure you have the latest version of node.js and npm installed.
126052 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
126052 error not with npm itself.
126052 error Tell the author that this fails on your system:
126052 error     node install.js
126052 error You can get information on how to open an issue for this project with:
126052 error     npm bugs phantomjs-prebuilt
126052 error Or if that isn't available, you can get their info via:
126052 error     npm owner ls phantomjs-prebuilt
126052 error There is likely additional logging output above.
126053 verbose exit [ 1, true ]

**Comment by tovinayv** [comment]
Attaching npm-debug.log and package.json

[package.json.txt](https://github.com/Medium/phantomjs/files/896212/package.json.txt)
[npm-debug.log.txt](https://github.com/Medium/phantomjs/files/896208/npm-debug.log.txt)

**Comment by RiyadWu** [comment]
have the same problem in win10x64

**Comment by brokenarrows** [comment]
Try updating your nodeJS to latest.

e.g.

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by tovinayv** [comment]
Failed to install even with latest version of nodejs (7.9.0)

[ERROR] npm ERR! Linux 2.6.32-220.4.2.el6.x86_64
[ERROR] npm ERR! argv "/build/mts/release/sb-9082849/vrops-vcd-tenant-view/node/node" "/build/mts/release/sb-9082849/vrops-vcd-tenant-view/node/node_modules/npm/bin/npm-cli.js" "install" "phantomjs-prebuilt"
[ERROR] npm ERR! node v7.9.0
[ERROR] npm ERR! npm  v4.2.0
[ERROR] npm ERR! file sh
[ERROR] npm ERR! path sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn sh
[ERROR] 
[ERROR] npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
[ERROR] npm ERR! spawn sh ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node install.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs phantomjs-prebuilt
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls phantomjs-prebuilt
[ERROR] npm ERR! There is likely additional logging output above.

**Comment by tovinayv** [comment]
There was a problem with my env. bzip2 was not in my PATH

**Comment by wiolken44** [comment]
_brokenarrows_ -> curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs   - that helped me. 

Thank you :)
