### ISSUE TITLE
Vulnerability in sub-dependency, "debug"

### ISSUE THREAD

**Issue by avindra** [Medium/phantomjs#745]
PR is made upstream for the fix

https://github.com/maxogden/extract-zip/pull/52

`phantomjs` will  also need to unlock the version number or bump it so that upgrades will pass through.

**Comment by avindra** [comment]
I would recommend using `^` in the `dependencies`, so that upgrades will automatically pass through, particularly because Medium has expressed that they are not interested in maintaining this package.

**Comment by kgrubb** [comment]
Extract-zip has been updated with a newer version of `debug` in [94b877a](https://github.com/maxogden/extract-zip/commit/94b877a54dfaac8ada949cf385afb41fa0102099). According to [NSP](https://nodesecurity.io/check/phantomjs-prebuilt), there are no longer any known vulnerabilities for phantomjs-prebuilt! 🍰

**Comment by avindra** [comment]
@kgrubb NSP is incorrect. `phantomjs-prebuilt` still has to bump it's dependencies, or change the tilde to a caret to allow semver updates automatically.

PR here for the latter: https://github.com/Medium/phantomjs/pull/746

**Comment by kgrubb** [comment]
Oh duh, my apologies. I completely overlooked the package.json upgrade required for this package.

**Comment by avindra** [comment]
No worries. It seems that NSP needs to take into account how dependencies are resolved using semver in node land.

**Comment by avindra** [comment]
@kgrubb I was wrong.

Tilde means patch upgrades are allowed:

https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1

So NSP is correct, and this particular issue, is indeed fixed.
