### ISSUE TITLE
not able to install phantomjs

### ISSUE THREAD

**Issue by SnehalBhavsar** [Medium/phantomjs#784]
C:\Users\snehal.bhavsar\myGreatApp>npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.16 install C:\Users\snehal.bhavsar\myGreatApp\node_modu
les\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantom
js-2.1.1-windows.zip
Saving to C:\Users\SNEHAL~1.BHA\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-win
dows.zip
Receiving...

Error making request.
Error: connect ECONNREFUSED 192.30.253.113:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\snehal.bhavsar\AppData\Roaming\npm-cache\_logs\2018-03-13T
09_43_31_861Z-debug.log

C:\Users\snehal.bhavsar\myGreatApp>npm install phantomjs-prebuilt

**Comment by SnehalBhavsar** [comment]
fixed it.. it was proxy issue

**Comment by crystalwm** [comment]
@SnehalBhavsar I also have the same issue . How to set the proxy?

**Comment by SnehalBhavsar** [comment]
You can below command

npm  config set proxy http://<username>:<password>@<proxy server url or
up>:<port>
