### ISSUE TITLE
Installing Node and PhantomJS not found on PATH

### ISSUE THREAD

**Issue by djmill2** [Medium/phantomjs#802]
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\Louise\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN webpack-fail-plugin@1.0.6 requires a peer of webpack@^1.9.11 but none is installed. You must install peer dependencies yourself.
npm WARN mytodo No description
npm WARN mytodo No repository field.
npm WARN mytodo No license field.
npm WARN The package es6-shim is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The full log for this install is:

[2018-06-22T15_13_49_460Z-debug.log](https://github.com/Medium/phantomjs/files/2128198/2018-06-22T15_13_49_460Z-debug.log)

**Comment by jdg223** [comment]
Check your proxy settings
