### ISSUE TITLE
Mark deprecated

### ISSUE THREAD

**Issue by wbt** [Medium/phantomjs#825]
Maintenance of the underlying phantomjs library was suspended last year, following [an](https://carstenwindler.de/software-testing/phantomjs-is-discontinued/) [announcement](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) the year before.  Nowhere in the readme (republished on [npm](https://www.npmjs.com/package/phantomjs-prebuilt)) is this mentioned, and the opposite impression is given by its first full sentences:

>What this installer is really doing is just grabbing a particular "blessed" (by this module) version of Phantom. As new versions of Phantom are released and vetted, this module will be updated accordingly.

The PhantomJS link at the start of the readme points to [that project's official website](https://phantomjs.org/), which opens by saying:

>Important: PhantomJS development is suspended until further notice ([more details](https://github.com/ariya/phantomjs/issues/15344)).

The last publish of the library, as noted on the [NPM page](https://www.npmjs.com/package/phantomjs-prebuilt), was 2 years ago.  There are [vulnerabilities in dependencies](https://github.com/Medium/phantomjs/issues/819) and other [issues](https://github.com/ariya/phantomjs/issues) in functionality. 

**This package should be [marked as deprecated](https://docs.npmjs.com/cli/deprecate) in NPM.**  
Explanatory text should also be added to the readme.  

Doing so will help reduce the number of projects adding this as a dependency and encourage projects already using it to shift to something more maintained, like headless Chrome. 

This would take relatively little time from @Medium which is clearly still in operation, and could help reduce the flow of incoming Issues and associated attention requirements.  @valueof, do you have permissions to do this?

(My ability to investigate further details is blocked by some [serious issues with GitHub going on now](https://www.githubstatus.com/incidents/tq7pm7mn9b1k), so I'm filing this Issue while it still seems possible to do so.)

**Comment by valueof** [comment]
Thanks for raising this. Let me see if I can deprecate the package.

**Comment by wbt** [comment]
Thanks! Please also do the same with [bundled-phantomjs-prebuilt](https://www.npmjs.com/package/).

**Comment by zeevl** [comment]
Done.   Thanks for the poke!

**Comment by valueof** [comment]
I've deprecated our NPM package. Unfortunately, we don't have access to the other three packages since they are maintained by the outside developers. I've also updated the README and going to archive this repo shortly.

Again, thank you for raising this, @wbt, I really appreciate it.
