### ISSUE TITLE
PhantomJS Releases not found ?

### ISSUE THREAD

**Issue by Prechan** [Medium/phantomjs#826]
Hi,

We use PhantomJS in a project, as thousands of people around here (even if it's deprecated).
Just right now in our pipeline, and in my computer I'm no more able to download and use release of PhantomJS.

When I try to install it from npm, I get an error:

> PhantomJS not found on PATH
> Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
> Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
> Receiving...
> 
> Error requesting archive.
> Status: 500
> Request options: {
> [...]
> }

Any idea about what's going on ? The release page is out: https://github.com/Medium/phantomjs/releases

Thank you !

**Comment by wbt** [comment]
GitHub is having some serious issues at present with a lot of its pages, affecting this repo.  You can probably track status [here](https://www.githubstatus.com/incidents/tq7pm7mn9b1k) for updates.

**Comment by Prechan** [comment]
> 
> 
> GitHub is having some serious issues at present with a lot of its pages, affecting this repo. You can probably track status [here](https://www.githubstatus.com/incidents/tq7pm7mn9b1k) for updates.

Thank you, that was it indeed !
