### ISSUE TITLE
Error on install using NPM : https://registry.npmjs.org/%E2%80%93g doesn't exist in repository

### ISSUE THREAD

**Issue by iangregsondev** [Medium/phantomjs#98]
After doing a

   Npm install -g phantomjs

npm http GET https://registry.npmjs.org/%E2%80%93g
npm http GET https://registry.npmjs.org/phantomjs
npm http 304 https://registry.npmjs.org/phantomjs
npm http 404 https://registry.npmjs.org/%E2%80%93g
npm ERR! 404 '%E2%80%93g' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

It did work the other day, anybody getting the same issue ?

I tried removing the cache folder but still the same.

**Comment by shmdhussain** [comment]
Thanks dpup for the help. the issue is i copied the npm command from MS word. the "hyphen" is the problem, now i put in some editor and changed now it is working
